### ISSUE TITLE
doc_ids don't line up using the docs_bulk function.

### ISSUE THREAD

**Issue by jhendric98** [ropensci/elastic#123]
Loading an elasticsearch index from a data.frame of about 125,000 observations and using the first variable as the argument for the doc_ids doesn't load the doc_ids correctly. It seems to load one row off.

docs_bulk(product,index = "model",type = "hd", doc_ids = product$productid)

product has 2 variables =>  productid and description

_id : 503
productid: 504
descscription: "4 drawer dresser, black"

My first productid is 101 and the first _id gets 100 assigned.

**Comment by sckott** [comment]
Thanks for the report. I remember there being a good reason to force zero based document IDs, so I do that https://github.com/ropensci/elastic/blob/master/R/docs_bulk.r#L226 when the ids are numeric. However, for user supplied I guess we should not do that

**Comment by sckott** [comment]
I wish I could remember what that reason was

**Comment by jhendric98** [comment]
In every use case I currently have, the document id has significance as a relational key field that tries more than a single incoming dataset together. In the use case above, the productid is created from external systems that transactionally manage a product master. I have to provide search capacity to the underlying RDBMS as the search load on the system is overcoming the capacity to conduct transactions. 

I'm sure there are use cases where simple sequential ids are a valid scheme, but one could use the default _id.

**Comment by sckott** [comment]
@jhendric98 okay reinstall like `devtools::install_github("ropensci/elastic")`, and try again

You should get the same doc ids you pass in to the function

see also #125

**Comment by jhendric98** [comment]
great. I had just forked the project myself. I'll test it out in just a few hours when I get to my computer and let you know.

**Comment by jhendric98** [comment]
Worked fine thanks.

**Comment by sckott** [comment]
great!

**Comment by sckott** [comment]
closing, pushing #125 soon
