### ISSUE TITLE
More-like-this query always returns zero scores

### ISSUE THREAD

**Issue by jenkin** [ropensci/elastic#126]
Hi, I'm using scan and scroll api (ie. last example [here](https://cran.r-project.org/web/packages/elastic/vignettes/search.html)) to fetch all documents similar to others (see [mlt query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html)). All works fine, but scoring for all returned documents is always zero. If I directly run the same query (ie. in Sense), the result is the same, but with correct scores. Is there a problem during  conversion from json to R data structures? Thanks! :)

**Comment by sckott** [comment]
thanks for the report @jenkin - I'll have a look now

**Comment by sckott** [comment]
I believe scores are not tracked when scrolling (See http://mail-archives.us.apache.org/mod_mbox/spark-user/201504.mbox/%3C1429349001763.b5aa674f@Nodemailer%3E), so all are reported as zero

> If I directly run the same query (ie. in Sense), the result is the same, but with correct scores

but are you scrolling in the Sense GUI?

**Comment by jenkin** [comment]
D'oh! Thank you, I missed this detail in scan&scroll feature of ES... just now I'm trying with python library and score is always zero. And no, in Sense I performed simple query, without scrolling. Ok, nevermind, I'll use simple pagination to retrieve first N results, sorry for this "not-so" issue... :)

**Comment by sckott** [comment]
No problem. I had forgotten about scores for scroll, I'll add a note to the docs if not already there
