### ISSUE TITLE
Error on `connect()` when ElasticSearch is accessed through a proxy

### ISSUE THREAD

**Issue by wsams** [ropensci/elastic#137]
Hi, I'm working on a project that has ElasticSearch set up through a proxy in Apache. For example, the Apache configuration looks like this,

	ProxyPass /my-es http://example.com:10001 retry=0 connectiontimeout=300 timeout=300
	ProxyPassReverse /my-es http://example.com:10001
	
https://secure.com is secure behind 443 so that we can use BasicAuth in front of ES.
	
I can run `curl https://secure.com/my-es -u joefoo` to verify that the ES instance is alive.
	
When I try the following it exits immediately with `Error:` and nothing more.

	library("elastic")

	connect(es_host = "secure.com/my-es", es_port = 10001, es_user = "foobar", es_pwd = "blah", es_transport_schema = "https")

I'm assuming this is a bug, but maybe I'm not using the library correctly. Does the `elastic` library support a context path, or must `es_host` be an IP or hostname? Many thanks for your help. If I can provide any other details, please let me know.

**Comment by sckott** [comment]
Sorry for the delay - was on vacation. 

I'm guessing that's a bug. I'll have a look and see what's going on

**Comment by sckott** [comment]
@wsams Via the `...` in `connect()` you can pass in proxy settings to the `headers` parameter - did you try that yet? You can pass in proxy settings via `httr::use_proxy()` to `headers` param 

One problem is in `connect()` it pings the ES server to make sure its up, but doesn't include headers right now, i'll fix that

**Comment by wsams** [comment]
Hi @sckott, I don't believe `httr::use_proxy()` is going to work since our proxy is in Apache - we're not going through an internet proxy to talk to ElasticSearch.

**Comment by wsams** [comment]
@sckott, I see what could likely be the culprit. After checking on the source and adding some debugging statements I see that the `baseurl` equates to,
```
https://secure.com/my-es:443
```
`:443` should be moved after `.com` like this,
```
https://secure.com:443/my-es
```
I might be able to create a patch, but I'm not normally an `r` developer.

**Comment by wsams** [comment]
I started a branch here https://github.com/wsams/elastic/blob/context-path/R/connect.R if you want to see what I was trying to do.

**Comment by sckott** [comment]
@wsams Thanks for sorting this out, been busy lately.  Having a look

**Comment by sckott** [comment]
@wsams 

> Edit: Now that I'm thinking about it, it may be easier to pass in the context path to connect() instead of parsing the URL.

So perhaps use one of the following options:

* add a new parameter (e.g., `es_url`) to `connect()` which takes the complete url, including scheme, host, port, context path, and then all other params that are used to construct the url are ignored, or
* add a new parameter for the context path (e.g., `es_path`) to `connect()` which takes the context path, and uses it if given to construct the url

thoughts?

**Comment by wsams** [comment]
Both of those sound like reasonable solutions. I'm leaning towards the second solution since the other parts are already broken out of the full url as arguments.

**Comment by sckott** [comment]
Install from github, made some changes,  let me know if it works now

**Comment by wsams** [comment]
@sckott, that did it, thanks a lot for helping.

**Comment by sckott** [comment]
great, glad it works now
