### ISSUE TITLE
Bug in docs_bulk.character

### ISSUE THREAD

**Issue by steeled** [ropensci/elastic#141]
Url is using conn$base, but should be conn$host (from es_get_auth)

**Comment by sckott** [comment]
woops. thanks for catching that

**Comment by sckott** [comment]
@steeled sorry about that, reinstall from github `devtools::install_github("ropensci/elastic")` - adding some more tests

**Comment by sckott** [comment]
sorted

**Comment by steeled** [comment]
Thanks for sharing!
