### ISSUE TITLE
wildcards in index name

### ISSUE THREAD

**Issue by martijnvanbeers** [ropensci/elastic#143]
When I installed elasticdsl today, the elastic library seems to have gotten updated (to 0.7.2; unfortunately I have no idea what version I had before), and since then I get the following error when I try to use a * wildcard when specifying an index:

> `> tweets <- Search(index="tweet3-2016.*", asdf = T, size = 10000)$hits$hits$'_source'
Error: 404 - IndexMissingException[[tweet3-2016.%2A] missing]`

I know I can specify multiple indices, but that gets tedious fairly quickly if you have daily indices, so I'm hoping that either I missed a new way to do wildcards, or that this functionality can be brought back.

**Comment by sckott** [comment]
@martijnvanbeers thanks for your question. I'll have a look and get back to you

**Comment by sckott** [comment]
Hmmm, I originally used url escaping to make sure indexes and type's with special characters worked (#49 )

**Comment by sckott** [comment]
@martijnvanbeers Okay, reinstall `devtools::install_github("ropensci/elastic")` then try again and let me know if it works

**Comment by martijnvanbeers** [comment]
@sckott yes, that works. awesome, thanks!
