### ISSUE TITLE
docs_delete with non-numeric ID's

### ISSUE THREAD

**Issue by dominoFire** [ropensci/elastic#144]
It would be nice if `elastic::docs_delete` could accept non numeric ID's. For example:

```
elastic::docs_delete(index="counter", type="cnt", id="AVYuZPYMnFJ8C9A9OiCo") 
```

You can have non-numeric document ID's when you let elasticsearch assign ID's

**Comment by sckott** [comment]
@dominoFire  thanks for the report. 

The docs for this function do say that it should be `numeric`, but it does accept character as well. e.g. 

```r
docs_bulk(mtcars, "mtcars")

docs_get("mtcars", "mtcars", id = "AVYlFNh4P15xxvkkHPjG") # found
docs_delete("mtcars", "mtcars", id = "AVYlFNh4P15xxvkkHPjG")
docs_get("mtcars", "mtcars", id = "AVYlFNh4P15xxvkkHPjG") # not found
```

your ids will be diff. of course

**Comment by sckott** [comment]
if you reinstall the docs are updated
