### ISSUE TITLE
Connecting to ES with shield

### ISSUE THREAD

**Issue by kickbox** [ropensci/elastic#148]
When trying to connect to a ES database with shield,

`elastic::connect(es_base = 'https://prod.company.com',es_port = 6379,errors="complete", es_user = "myname", es_pwd = "password")`

I get the following error 

```
Error: 
  Failed to connect to https://prod.company.com:6379
  Remember to start Elasticsearch before connecting
```

Is there something wrong that I am doing here?

**Comment by sckott** [comment]
thanks for the report. 

This is not really testable for me since Shield is a paid product. Do you know if they have free versions for client developers?

What kind of auth does Shield do?  Simple auth like `user:pwd` or something else?

**Comment by kickbox** [comment]
Hi @sckott  Iam not familiar with this myself.  I came across this link, https://www.elastic.co/guide/en/shield/current/_using_elasticsearch_http_rest_clients_with_shield.html
Hope this helps. If not I can check more with my IT team if you want.

**Comment by kickbox** [comment]
As with your first query. This answer should help http://stackoverflow.com/questions/32196483/where-to-get-elasticsearch-shield-license

Meanwhile I would suggest that you contact them. You are doing great work for the entire R and elastic search community, they should support you for free.

**Comment by sckott** [comment]
Thanks for the links, I might ask if they can give me access for free.

**Comment by sckott** [comment]
Try this:

```r
library("httr")
library("jsonlite")
user <- "Aladdin"
pwd <- "OpenSesame"
connect(
  headers = add_headers(
    Authorization = 
      paste0("Basic ", base64_enc(paste0(user, ":", pwd)))
  )
)
x <- Search(config=verbose())
```

replace with your username and password for Shield

the `x <- Search(config=verbose())` should print e..g, 

```r
#> -> POST /_search?version=false&lenient=false HTTP/1.1
#> -> Host: 127.0.0.1:9200
#> -> User-Agent: libcurl/7.43.0 r-curl/1.2 httr/1.2.1
#> -> Accept-Encoding: gzip, deflate
#> -> Accept: application/json, text/xml, application/xml, */*
#> -> Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l
#> -> Content-Length: 0
#> -> 
#> <- HTTP/1.1 200 OK
#> <- Content-Type: application/json; charset=UTF-8
#> <- Content-Length: 1596
#> <- 
```

that header you set in `connect()` should be sent on each request

**Comment by kickbox** [comment]
I tried this
```
connect(es_host = "es.mycompany.com",es_port = 9200, es_transport_schema="https" ,  headers = add_headers(
    Authorization = paste0("Basic ", base64_enc(paste0(user, ":", pwd)))
  )
)
```
It resulted in 
```
transport:  https 
host:       es.mycompany.com 
port:       9200 
path:       NULL 
username:   NULL 
password:   <secret> 
errors:     simple 
headers (names):  Authorization
> x <- Search(config=verbose())
Error: Check your connection, server may be down, url or port incorrect, or authentication wrong
```

**Comment by sckott** [comment]
Hmm, instead of setting the header in the `connect()` call, try adding the header in via `config` param in your `Search` call, like 

```r
Search(
  config = add_headers(
    Authorization = 
      paste0("Basic ", base64_enc(paste0(user, ":", pwd)))
  )
)
```

**Comment by kickbox** [comment]
Unfortunately I get the same error :(

```
elastic::connect(es_host = 'es.mycompany.com', es_transport_schema="https://" , es_port = 9200) 

newx <- Search(index="myIndex",sort="@timestamp:desc", size="50",
  config = add_headers(
  Authorization = paste0("Basic ", base64_enc(paste0(user, ":", pwd)))
  )
)
```
`Error: Check your connection, server may be down, url or port incorrect, or authentication wrong`

**Comment by sckott** [comment]
@kickbox try again after reinstalling from github `devtools::install_github("ropensci/elastic")`

3 different methods should work now, **I think**

```r
library("httr")
library("jsonlite")

# user and pwd
user <- "Aladdin"
pwd <- "OpenSesame"

## method 1 - pass variables in connect() call
connect(es_user = user, es_pwd = pwd)
x <- Search(
  config = verbose()
)

## method 2 - adde headers to connect() call
connect(
  headers = add_headers(
    Authorization =
      paste0("Basic ", base64_enc(paste0(user, ":", pwd)))
  )
)
x <- Search(
  config = verbose()
)

## method 3 - add headers to each ES server request
connect()
x <- Search(
  config = c(
    add_headers(
      Authorization =
        paste0("Basic ", base64_enc(paste0(user, ":", pwd)))
    ),
    verbose()
  )
)
```

try the 1st first, and others after. let me know if it works or doesn't

**Comment by kickbox** [comment]
When I use all the above 3 cases with ` es_transport_schema="https"` (which is what I want),  I get, 

```
-> CONNECT es.mycompany.com:9200 HTTP/1.1
-> Host: es.mycompany.com:9200
-> Proxy-Authorization: Basic ZQ1tYW51ZQw6
-> User-Agent: libcurl/7.47.1 r-curl/1.2 httr/1.2.0
-> Proxy-Connection: Keep-Alive
-> 
<- HTTP/1.1 200 Connection established
<- 
Error: Check your connection, server may be down, url or port incorrect, or authentication wrong
```
with ` es_transport_schema="http"` (just for testing),  I get, 

```
-> HEAD http://es.mycompany.com:9200/ HTTP/1.1
-> Host: es.mycompany.com:9200
-> Proxy-Authorization: Basic ZQ1tYQ51ZWw6
-> Authorization: Basic ZQ1tYW51ZQw6d29yZHBhc3NRMSFqdQ4xNg==
-> User-Agent: libcurl/7.47.1 r-curl/1.2 httr/1.2.0
-> Accept-Encoding: gzip, deflate
-> Proxy-Connection: Keep-Alive
-> Accept: application/json, text/xml, application/xml, */*
-> 
<- HTTP/1.1 503 Service Unavailable
<- Cache-Control: no-cache
<- Pragma: no-cache
<- Content-Type: text/html; charset=utf-8
<- Proxy-Connection: Keep-Alive
<- Connection: Keep-Alive
<- Content-Length: 895
<- 
-> POST http://es.mycompany.com:9200/_search?version=false&lenient=false HTTP/1.1
-> Host: es.mycompany.com:9200
-> Proxy-Authorization: Basic ZQ1tYQ51ZWw6
-> Authorization: Basic ZQ1tYW51ZQw6d29yZHBhc3NRMSFqdQ4xNg==
-> User-Agent: libcurl/7.47.1 r-curl/1.2 httr/1.2.0
-> Accept-Encoding: gzip, deflate
-> Proxy-Connection: Keep-Alive
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Length: 0
-> 
<- HTTP/1.1 503 Service Unavailable
<- Cache-Control: no-cache
<- Pragma: no-cache
<- Content-Type: text/html; charset=utf-8
<- Proxy-Connection: Keep-Alive
<- Connection: Keep-Alive
<- Content-Length: 895
<- 
Error: lexical error: invalid char in json text.
                                       <HTML><HEAD>  <TITLE>Network Er
                     (right here) ------^
```

**Comment by sckott** [comment]
Thanks for this. It looks like you're also using a proxy?

**Comment by kickbox** [comment]
Yes. I use this command which works, to install packages from github, before a install_github() 
```
set_config(
  use_proxy(url="url", port=8080, username="user",password="password")
)
```

I tried this too before "connect" and "Search", and the results were the same.

**Comment by sckott** [comment]
Thanks for the additional details.

**Comment by kickbox** [comment]
@sckott would it be possible for you to suggest a workaround till you find a final solution, please?

**Comment by sckott** [comment]
I would love to, but I am out of ideas. The only thing I can think is to use the http client we use inside this pkg (`httr`) manually to play around with the authentication to see what works. Can just use the base elasticsearch URL or any route you like, and see what works for auth. What I mean is outside of this package, just try with `httr` to make a successful request. If you can find something that works, then I can implement within the package. Unfortunately, I don't have access to Shield so cannot try mysel

**Comment by kickbox** [comment]
Hi, I wonder if proxy should be a problem atall. Because I am accessing ES from within the network. Anyways, I successfully retrieved data using httr package, without setting any proxy by 

```
library("httr")
set_config( config( ssl)verifypeer = 0L))
url = "https://es.mycompany.com:9200/indexName/_search"
data= GET(url, authenticate("user", "password")
```
looking at data, I get this.
```
data
Response [HYPERLINK "https://es.mycompany.com:9200/indexName/_search"https://es.mycompany.com:9200/indexName/_search]
Date: 2016-09-30 14:26
  Status: 200
  Content-Type: application/json; charset=UTF-8
  Size: 643 kB
```
looking at content(data)
`content(data)`
I can see the ES data hits in the results

**Comment by sckott** [comment]
I'm glad that worked for you. The only thing different I can tell is that you set verify peer FALSE - which is not a good idea in general i think. 

I just installed the trail version of Shield on my local machine following instructions at https://www.elastic.co/downloads/shield (or here https://www.elastic.co/guide/en/shield/current/getting-started.html - same thing). It worked with the following:

```r
library("elastic")
connect(es_user = "es_admin",  es_pwd = "helloworld")
Search() # worked
cat_indices() # worked
```

So, I'm not sure why it's not working for you. If you want, you can email me headers so I can see what might be going wrong, but I imagine that's not possible

p.s., here's the issue I opened on the Elastic forum https://discuss.elastic.co/t/shield-license-for-elasticsearch-client-library-maintainers/60656

**Comment by kickbox** [comment]
@sckott, I tried again with 
```
httr::set_config( config( ssl)verifypeer = 0L))
connect(es_host = 'elk.mycompany.com', es_transport_schema="https",es_port = 9200,
                 es_user = user, es_pwd = pwd)
```

Everything works now Iam using your plugin again. Thanks.

**Comment by sckott** [comment]
@kickbox great, glad it works now
