### ISSUE TITLE
Connecting to AWS ES - 404 Error

### ISSUE THREAD

**Issue by nelsonSchwarz** [ropensci/elastic#157]
I cannot seem to connect to Elasticsearch on Amazon Web Services. I keep getting this error 

`Error: 404 - no such index`
`ES stack trace:`
`  type: index_not_found_exception`
`  reason: no such index`
`  resource.type: index_or_alias`
`  resource.id: us-east-1.es.amazonaws.com`
`  index: us-east-1.es.amazonaws.com`

when I use this:

`connect(es_host = aws_endpoint, 
    es_port = 80,
    errors = "complete")`
`ping()`

To spare redundancy, please see full issue here:
http://stackoverflow.com/questions/40895027/connecting-to-aws-elasticsearch-service-using-r-getting-404-error

How do I establish an approriate connection between R and AWS ES?

**Comment by nelsonSchwarz** [comment]
Solved it:
`connect(es_host = aws_endpoint, es_port = 80, errors = "complete", es_path = "")`
`es_path` must be specified as empty string. Using NULL does not work.

**Comment by sckott** [comment]
thanks for the issue and the PR

**Comment by nelsonSchwarz** [comment]
No, thank you for the package!
