### ISSUE TITLE
Feature request: Progress bar for queries

### ISSUE THREAD

**Issue by kickbox** [ropensci/elastic#162]
@sckott I frequently query large data from ES through your plugin. However I am not able to see if the query is active/inactive or progressing. Can you please add a feature where we can track the data-download progress of the search?  

Something like this could be handy in tracking the progress of the query -https://github.com/gaborcsardi/progress.

**Comment by sckott** [comment]
thanks for the issue, will have a look in the morning

**Comment by sckott** [comment]
I think the best way to do this that works across functions, is via `httr::progress()` - that can be passed in to most if not all `elastic` functions, e.g, 

`Search(config = progress(), size = 5000)` 

you have to pass it in with the named variable `config` 

I'll add examples to the docs soon
