### ISSUE TITLE
scroll with asdf = TRUE ?

### ISSUE THREAD

**Issue by joelgombin** [ropensci/elastic#163]
If my initial `Search` uses the `asdf = TRUE` argument, is it possible to then make sure that `scroll` returns objects consistent with the one returned by the initial `Search`?

Alternatively, can I easily bind the lists and then make sure to get a dataframe?

**Comment by sckott** [comment]
thanks @joelgombin 

this is somewhat related to #160  in which experimenting with `jsonlite::stream_in`  which allows a custom handler to determine how each JSON page is parsed. 

pushing something up soon. 

we maybe can just add the `asdf` param to `scroll`, as we call `jsonlite::fromJSON(res, FALSE)` inside `scroll` and if we have `asdf` in `scroll` then we can do `jsonlite::fromJSON(res, asdf)` to let use control output

**Comment by joelgombin** [comment]
I think an `asdf` param to `scroll` would make a lot of sense.
Alternatively, I realised that by passing a query to the `body` argument, I can go around the 10000 observations limit of `Search`:

```r
query <- '{
  "from": 0,
"size": 1000000,
....
}'

Search(body = query, asdf = TRUE, scroll = "5m")
```

**Comment by sckott** [comment]
@joelgombin reinstall and try again, added `asdf` parameter to `scroll`

**Comment by joelgombin** [comment]
Thanks, that works!
