### ISSUE TITLE
Types starting to go away

### ISSUE THREAD

**Issue by sckott** [ropensci/elastic#180]
https://github.com/elastic/elasticsearch/issues/15613#issuecomment-303727982

erroring now, not allowing > 1 type per index 

Note: will also need to change example datasets to one type per index

e.g. using `elasticsearch-6.0.0-alpha2`

```r
shakespeare <- system.file("examples", "shakespeare_data.json", package = "elastic")
invisible(docs_bulk(shakespeare))
```

```
[2017-06-09T06:57:39,368][DEBUG][o.e.a.b.TransportShardBulkAction] [shakespeare][4] failed to execute bulk item (index) BulkShardRequest [[shakespeare][4]] containing [1049] requests
java.lang.IllegalArgumentException: Rejecting mapping update to [shakespeare] as the final mapping would have more than 1 type: [line, scene]
```

**Comment by gerasimos** [comment]
Some problem using 6.0.0-rc1

**Comment by sckott** [comment]
@ gerasimos i got an email notification that you said on this issue

> Some problem using 6.0.0-rc1

but now it's gone. did you delete it (and thus i'll just forget about it) or maybe you posted and github somehow lost it (in which case I'll make sure to consider it)

**Comment by gerasimos** [comment]
I delete it, because I understood that it was not a bug but an issue related to the maintenance of the documentation.

**Comment by sckott** [comment]
okay, thx

**Comment by sckott** [comment]
still to do:

- [ ] add egs of using `type_remover()` fxn to remove `_type` in bulk eg files so they will work in older and newer ES
- [ ] ...
