### ISSUE TITLE
unnecessary multiple ping() calls to get ES version

### ISSUE THREAD

**Issue by henfiber** [ropensci/elastic#184]
Hello there. After profiling some ES queries, I noticed that the minimum request time was about 300 milliseconds and found out that this is in large (the 200ms, about 65%) due to the multiple `ping()$version$number` checks in `search_POST()` and `search_GET()`. You may have not noticed it during development with a local server, but makes a large difference when ES is behind a distant network. (In my use case, each ping() roundtrip takes about 80-110 ms)

e.g. at [search.r](https://github.com/ropensci/elastic/blob/master/R/search.r#L54-L56) and [Search_uri.R](https://github.com/ropensci/elastic/blob/master/R/Search_uri.R#L41-L43)

```
# in ES >= v5, lenient param droppped
if (gsub("\\.", "", ping()$version$number) >= 500) args$lenient <- NULL
# in ES >= v5, fields param changed to stored_fields
if (gsub("\\.", "", ping()$version$number) >= 500) { ... }
```

the second ping() call could be saved by saving the result of the first call. Or probably totally avoided if the version is cached in the session variables during the first `ping()` call in that session (should be invalidated after a next connect() call, since the server and version may be different).

**Comment by sckott** [comment]
thanks for the issue @henfiber 

Right, i probably didn't notice due to testing on local server instance. 

I'll cache the ES version and reuse it

**Comment by henfiber** [comment]
thanks @sckott much appreciated
