### ISSUE TITLE
ingest API

### ISSUE THREAD

**Issue by sckott** [ropensci/elastic#191]
https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest-apis.html

**Comment by dbuijs** [comment]
Temporary workaround to use pipelines (that you've already defined):

    docs_bulk(my_data_frame, index = "my_index", type = "my_row", query = "pipeline=my_pipeline")

**Comment by sckott** [comment]
thanks @dbuijs will have a look

**Comment by sckott** [comment]
SO question related https://stackoverflow.com/questions/51365187/index-files-using-r-and-elastic

**Comment by Jensxy** [comment]
How to use the workaround for arrays?

**Comment by sckott** [comment]
done in 6be1f45

**Comment by sckott** [comment]
@dbuijs @Jensxy just added ingest/pipeline fxns, reinstall `remotes::install_github("ropensci/elastic")` and see `?ingest`

**Comment by sckott** [comment]
sorry, not sure how to do that
