### ISSUE TITLE
quiet argument

### ISSUE THREAD

**Issue by emillykkejensen** [ropensci/elastic#202]
The progress bar is a nice touch - but it could be nice, if it could be turned off!

**Comment by sckott** [comment]
for what function(s)?

**Comment by emillykkejensen** [comment]
docs_bulk.data.frame() in docs_bulk.r

One way to do it, would be to add an extra logical argument called 'quiet'

The on line 213/214 and line 217 add if(quiet)

**Comment by sckott** [comment]
@emillykkejensen reinstall and try again , see `quiet` param
