### ISSUE TITLE
Accessing server which uses basic auth for authentication

### ISSUE THREAD

**Issue by dkincaid** [ropensci/elastic#204]
We use nginx with basic auth to front our ES server. It seems like it's not currently possible to connect to this server with this package. So this is a request to add that functionality.

**Comment by sckott** [comment]
does this work https://github.com/ropensci/elastic/issues/177#issuecomment-305050990 for you?  if not, i'll look into it

**Comment by dkincaid** [comment]
Right now I'm getting this:

`> esconn <- elastic::connect(es_host = eshost, es_port = esport, es_user = "esprd", es_pwd = "password", es_path = "")
> elastic::ping(esconn)
Error: 400 - request [/] contains unrecognized parameters: [errors], [host], [path], [port], [pwd], [transport], [user]`

**Comment by sckott** [comment]
`ping` doesn't take any parameters. can you do it again just calling it like `elastic::ping()`

**Comment by dkincaid** [comment]
Oh man. Sorry about that. Been a long day. Yeah that's working. Sorry for the trouble.

**Comment by sckott** [comment]
great, glad its working 👍
