### ISSUE TITLE
Document id required in docs_create function

### ISSUE THREAD

**Issue by jbrant** [ropensci/elastic#216]
It seems that the docs_create function requires a manually specified document ID. Why not make that an optional field and let Elasticsearch generate the ID?

**Comment by sckott** [comment]
thanks @jbrant - we have this already implemented in `docs_bulk`, but not here, i guess b/c nobody raise the issue yet. 

anyway, change made, reinstall `remotes::install_github("ropensci/elastic")` and try it again.

**Comment by jbrant** [comment]
Awesome - thank you!
