### ISSUE TITLE
Searching phrases

### ISSUE THREAD

**Issue by fissehab** [ropensci/elastic#222]
I want to search exact phrases. How can I do it? Basically, I want to use something like below

`"query": {
        "query_string" : {
            "type":       "phrase",
            "query" : "(cloud computing) OR (supply chain)"
        }
    }`

**Comment by sckott** [comment]
does this do what you want? https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-match-query-phrase.html

**Comment by fissehab** [comment]
Thanks. But how can I use that in R to search any of the phrases shown above?

**Comment by fissehab** [comment]
I have many phrases and also the phrases are dynamic. They are search input on a shiny app . Using [query string](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax) looks easier to implement if it is possible to search phrases. But with the above approach you provided, how can I search many phrases? By just repeating the "match_phrase" for each phrase?

**Comment by sckott** [comment]
i'm not sure. i'd google/search stackoverflow. or ask on the elasticsearch discussion forum https://discuss.elastic.co/

**Comment by sckott** [comment]
hopefully you've found an answer, it sort of falls out of scope of this package as it's more of a how to for Elasticsearch database itself
