### ISSUE TITLE
rework alias fxns

### ISSUE THREAD

**Issue by sckott** [ropensci/elastic#230]
via https://stackoverflow.com/questions/51782977/elastic-create-multiple-aliases-at-a-time-in-r 

seems that https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html instead of basing everything in URL's pass data in bodies to give more flexibility

**Comment by Jensxy** [comment]
Will you also add the possibility to delete more than one alias at a time?

**Comment by sckott** [comment]
will try

**Comment by sckott** [comment]
hmm, it seems there's a pattern to remove more than 1 alias per request https://github.com/elastic/elasticsearch/issues/15186#issuecomment-162029698 

not sure if this still works in the current version or. not, havne't tried yet
