### ISSUE TITLE
Docs suggestions

### ISSUE THREAD

**Issue by maelle** [ropensci/elastic#233]
Would you consider adding a pkgdown website to make vignettes easier to access?

I am reading https://ropensci.org/technotes/2017/08/02/elasticsearch-client/ and really like the "What is Elasticsearch?" paragraph. Is this already in the package docs somewhere? If not could it get added to e.g. the README?

**Comment by sckott** [comment]
we could do the pkgdown, but definitely can not do vignette rendering when the pkgdown builds the site cause it require elasticsearch to be running, so vignettes have to be pre-rendered

no, that paragraph isn't anywhere, we should add it

**Comment by maelle** [comment]
Having the whole thing built on Travis would be a nice challenge but probably not worth the effort 😁

**Comment by sckott** [comment]
yeah, i do test on travis with elasticsearch supported there, so it is possible

**Comment by maelle** [comment]
ah! It wouldn't avoid the CRAN vignette problem, but it'd make the site building easier. `travis` now has a magical `use_tic()` function (but it'd overwrite the Travis config file) that sets everything up for a deployment of the website on the gh-pages branch. I set it up in ropenscilabs/rodev yesterday to not have to remember to update the website.

**Comment by sckott** [comment]
i started to look at this, but this pkg has a man file called `index`, and that replaces the index.html file, so that's not good. I haven't seen a way to rename a reference .html file. have you?

**Comment by maelle** [comment]
Ah! That's unfortunate! I've made a PR with a hack, I have run `pkgdown::build_reference()` and the man html page was index-elastic.html which doesn't conflict with index.html the home page of the website. Obviously you might prefer to rename the homepage, which I'm not sure is possible without many efforts?

**Comment by sckott** [comment]
I would prefer if I could just rename the .html page for the index manual file, but seems not possible

i'll look over at the pr
