### ISSUE TITLE
es_ver(): what happens when an ES instance doesn't provide version information?

### ISSUE THREAD

**Issue by sckott** [ropensci/elastic#234]
via https://github.com/metacran/seer/issues/12

ES version information is essentially required to use this pkg. 

I think the solution might be to have a separate config option to either 

- pass the version info in directly/manually, e.,g. `connect(version = '1.3.9')`
- give a path that the version can be retrived from, has to be similar to what ES gives at the root path, but at a different path, e.g. `connect(ping_path = "/foo/bar")`
- let elastic pkg get the version as it does now from root path `/`

**Comment by sckott** [comment]
wil wait to see if others see this problem as well

**Comment by maelle** [comment]
I tried running

```r
conn <- elastic::connect(port = 80,
                         host = "search.r-pkg.org",
                         path = "package/_search")

elastic::Search(conn, q = 'Author = "Chamberlain"')
```

and ran into the problem mentioned in this issue. 

All the possibilities you mention seem ok to me, but in the case I haven't passed an argument and the package guesses the version from the root, I'd expect a message.

**Comment by sckott** [comment]
thanks @maelle having a look

**Comment by sckott** [comment]
seems like you don't actually need the `path` defined in `connect()`, eg.., 

```r
conn <- connect(port = 80, host = "search.r-pkg.org")
conn$ping()
conn$es_ver()
Search(conn, q = 'Author = "Salmon"')$hits$total
```

**Comment by maelle** [comment]
Oh, thank you! 🎉

**Comment by sckott** [comment]
closing, no other pings on this
