### ISSUE TITLE
Deleting multiple documents at once

### ISSUE THREAD

**Issue by Jensxy** [ropensci/elastic#237]
I would like to delete multiple documents from a index with a id. For example, I like to delete the documents with the ids test_6, test_7 and test_8. How do I use docs_delete to delete them all at once?

**Comment by sckott** [comment]
is it okay for your use case to do an lapply or for loop?  e.g., 

```r
ids <- c(1, 5, 8)
lapply(ids, function(z) docs_delete(index='plos', type='article', id=z))
```

there is the delete by query API, but we don't have it implemented yet https://github.com/ropensci/elastic/issues/195 - does the delete by query API do what you need?

**Comment by Jensxy** [comment]
Yes, I will use lapply. Thank you very much.

**Comment by Jensxy** [comment]
Okay, that would be nice because lapply takes very long. I don't know if delete by query would improve the performance.

**Comment by sckott** [comment]
i don't know if it would improve either, we'll see

**Comment by sckott** [comment]
@Jensxy this is implemented now. `remotes::install_github("ropensci/elastic@r6-conn")` see `docs_delete_by_query()`
