### ISSUE TITLE
Use source_excludes in docs_get

### ISSUE THREAD

**Issue by Jensxy** [ropensci/elastic#246]
Hi guys, 

I like to use `source_excludes` in the `docs_get` function. Something similar to `GET twitter/_doc/1/_source?_source_includes=*.id&_source_excludes=entities`. Is that somehow possible? I want to use `docs_get` because I think it is faster than `Search` to retrieve exactly one document, right?

If I would use `Search`, I would use the following body.

```
    body <- '{
                   "query": {
                   "ids" : {
                   "values" : ["id_1"]
                   }
                   },
                   "_source": {
                   "excludes": ["source_1", "source_2"]
                   }
  }'
```

Best regards,
Jens

**Comment by sckott** [comment]
thanks, i'll take a look soon

**Comment by sckott** [comment]
i don't know which is faster, haven't compared times.

**Comment by sckott** [comment]
added, on branch r6-conn, `remotes::install_github("ropensci/elastic@r6-conn")`
