### ISSUE TITLE
Add more search API fxns

### ISSUE THREAD

**Issue by sckott** [ropensci/elastic#25]

**Comment by sckott** [comment]
what the hell did i mean here... :frowning:

**Comment by herrcafe** [comment]
You prolly meant adding query criteria like time intervals, keywords, etc. Also an argument to search or scroll. 

-- 
mtb

Sent from my iPhone
(+1) 919-717-5266

**Comment by sckott** [comment]
@herrcafe thx! though I think I did scroll https://github.com/ropensci/elastic/commit/0eafa29f02aec6f22c6e25cd7f22300f81b6019a
