### ISSUE TITLE
move all egs to not using types

### ISSUE THREAD

**Issue by sckott** [ropensci/elastic#251]
see https://www.elastic.co/guide/en/elasticsearch/reference/7.0/removal-of-types.html

- in v7 types are deprecated
- in v8 types will be removed

**Comment by Aeilert** [comment]
Question: Does this include changing the behavior of : 

```r
if (is.null(type)) 
        type <- index
```
I think setting doc-type to the specified index name as a default option causes a lot of unwanted behavior in ES, especially with the upgrade to v7.

**Comment by sckott** [comment]
good question. i agree does make sense to get rid of that behavior of setting the type to index if type not given. opened an issue since it seems separate enough

**Comment by Aeilert** [comment]
Okey. Will open a separate issue.

**Comment by sckott** [comment]
work on branch `type-scrubbing`
