### ISSUE TITLE
[Question\Sugestion] Support WKT point conversion to geo_point type

### ISSUE THREAD

**Issue by 4nonym0us** [ropensci/elastic#252]
Having WKT support only for `geo_shape` and not for `geo_point` is a bit confusing because WKT specification has GeoPoint representation.

Would't it be good to have an option to use WKT's point syntax `POINT (X, Y)` for `geo_point` for consistency as support even for more complex WKT primitives and multipart geometries is already present for `geo_shape`?

**Comment by 4nonym0us** [comment]
Moving the issue to appropriate repository.

**Comment by sckott** [comment]
right, i was thinking you probably mean to ask this in https://github.com/elastic/elasticsearch

**Comment by 4nonym0us** [comment]
@sckott yeah, that's what I did. Sorry for opening issue here (had too much tabs opened in my browser and created issue here accidentally).
