### ISSUE TITLE
docs_bulk() - Rgui 3.4 ok.  RGui 3.6 argument x is missing with no default

### ISSUE THREAD

**Issue by symdeb** [ropensci/elastic#258]
![Rgui](https://user-images.githubusercontent.com/19564066/59329970-c41ab580-8d22-11e9-816f-fa40dfffaeaa.PNG)

Just follows the example instructions on https://ropensci.org/tutorials/elastic_tutorial/
Rgui 3.4 (Microsoft) and RGUI 3.6 gives different results.

**Comment by sckott** [comment]
Sorry, that's an older tutorial. Look at the docs here instead https://docs.ropensci.org/elastic/index.html

**Comment by symdeb** [comment]
Going to the opensci main webpage and following the tutorial link, then this will direct to the old "0.8.0" tutorial I mentioned and not the newer one.  Understandably, incumbent users may not have a problem with this suggest to update the main page to update the links. It's confusing for new uses of R and elastic as myself. I could not find the new API call method using "x" even by by  googling before I posted the message above. BTW I am using elastic 7.01. in a local instance with  docker which works fine for queries using Kibana , head etc..

I definitely must be missing something obvious because with the new tutorial both versions of R don't work
![Capture](https://user-images.githubusercontent.com/19564066/59397922-e6fba700-8dc0-11e9-80e6-743bee9012d3.PNG)

**Comment by symdeb** [comment]
Figured it out . The statement in the tutorial should be  x <- connect(port = 9200)

**Comment by sckott** [comment]
cleared it up in the readme, fixing the website now
