### ISSUE TITLE
Functions not compatible with ES 7.2 

### ISSUE THREAD

**Issue by paliwal90** [ropensci/elastic#259]
Hi, after moving to Elastic 7.2 new version, when I use your package, some queries e.g. Search and count are not behaving as it was with earlier version.
For e.g.
```count(index = INDEX_NAME, q="column1:value1")``` works fine.

But 
```count(index = INDEX_NAME, q="column1:value1 and column2:value2")``` does not work good. Is AND not compatible? Also aggregations queries doesn't work both in Search and count.

**Comment by paliwal90** [comment]
Also track_total_hit is not working with Search. In elasticsearch GET query e.g. https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-track-total-hits.html says that it should return total hits (not just 1000 and gte relation). But from your R package, in Search query, it doesn't work.

**Comment by sckott** [comment]
thanks @paliwal90 please also share the output of `sessionInfo()` when `elastic` is loaded

**Comment by sckott** [comment]
@paliwal90 please share `sessionInfo()` when `elastic` is loaded - or else i won't be able to help

**Comment by paliwal90** [comment]
Well. Made it work. Needed to change search with new param.
