### ISSUE TITLE
connect: Unable to connect to Elasticsearch server using connect

### ISSUE THREAD

**Issue by mayankgautam** [ropensci/elastic#263]
I'm trying out elastic package to connect to elasticsearch on my system. 

But I'm not able to connect using elastic package.

Here is the code that I've used with error message:

I've started the elasticsearch and have checked that the default page was opening in browser properly.

elasticon <- connect(port = 9200)
elasticon$info()

Error: 
  Failed to connect to http://127.0.0.1:9200
  Remember to start Elasticsearch before connecting

**Comment by sckott** [comment]
is Elasticsearch running on localhost/127.0.0.1 and port 9200?

**Comment by mayankgautam** [comment]
Yes, it is.

**Comment by sckott** [comment]
Okay, so is there a proxy or some authentication you need to connect to the ES running?

**Comment by mayankgautam** [comment]
Yes, I'm trying to connect behind a proxy. 

I've tried below methods to connect to the server:
set_config(use_proxy(url='http://XXX.XX.XX.XXX', XXXX, 'username@comp.com', 'password'))
set_proxy(proxy("'http://XXX.XX.XX.XXX:XXXX", user = "username@comp.com", pwd = "password"))

But still, I'm not able to connect.

**Comment by sckott** [comment]
`set_proxy` and  `proxy` are the correct fxns to use as the underlying http library is `crul`, not `httr`. try this:

```r
library(elastic)
library(crul)
set_proxy(proxy("'http://XXX.XX.XX.XXX:1234", user = "username@comp.com", pwd = "password"))
x = connect()
x$info(verbose=TRUE)
```

`verbose=TRUE` gives verbose curl output, and should give some useful info if the proxy configuration is not working
