### ISSUE TITLE
Scroll and ignore version

### ISSUE THREAD

**Issue by rfsaldanha** [ropensci/elastic#281]
I'm getting this error when `connect` has `ignore_version = TRUE` and try to use scroll:

`Error in extractr(ver, "[[:digit:]]+")[[1]] : índice fora de limites`

Reproducible example:

```
conn <- connect(host = "imunizacao-es.saude.gov.br", 
                transport_schema = "https", path = "",  port = "",
                user = "imunizacao_public", 
                pwd = "qlto5t&7r_@+#Tlstigi", 
                ignore_version = TRUE)

res <- Search(conn, index = index_name, asdf = TRUE, size = 10000, time_scroll = "30m")

res2 <- scroll(conn, res$`_scroll_id`, asdf = TRUE)
```

**Comment by sckott** [comment]
if you'd like i can re-open this PR you opened https://github.com/ropensci/elastic/pull/276 ?

**Comment by rfsaldanha** [comment]
Thank you! No need, I created a new pull request on master #282
