### ISSUE TITLE
how to specify "curl --insecure" for encryption with unregistered root certs

### ISSUE THREAD

**Issue by tedmoorman** [ropensci/elastic#286]
I'm trying to connect to a server with Elastic Search. This can be done in a linux terminal with the following script:
 `curl --insecure -XGET https://user:pwd@host:9200/` . When I use `transport_schema = "http"` in the `connect` function, I get an "empty reply from server" error. When I use `transport_schema = "https"`, I get a "Peer's Certificate issuer is not recognized" error. My IT people are telling me that this is because there is encryption but the root certs are not registered. Is there a way to specify this "--insecure" option in the `connect` function?

**Comment by tedmoorman** [comment]
I think I figured it out. `ssl_verifypeer = 0L` seems to do the trick.

**Comment by sckott** [comment]
yep, that's it 👍🏽
