### ISSUE TITLE
docs_bulk_create.list

### ISSUE THREAD

**Issue by blosloos** [ropensci/elastic#294]
Dear ropensci/elastic maintainer

Thanks a lot for keeping this package functional - its a great help for interfacing R with elasticsearch! 

I was in need to ingest an R list object into elasticsearch, and by extracting chuncks of your elastic source code it worked. Thus, I was wondering why there is no method docs_bulk_create.list exported by your package, but solely one for data.frames? Any obstacle in other elastic functions/methods that I missed for applying to class list? Thanks ...

**Comment by sckott** [comment]
i don't remember why we only suppored data.frame's - if you want lists supported the only way to make it happen is if you send a PR - i don't have time to write any new code on this

**Comment by blosloos** [comment]
Thank you for your reply, I totally understand. I will check if I can find some time to work on a PR for list processing.
