### ISSUE TITLE
query argument not working

### ISSUE THREAD

**Issue by herrcafe** [ropensci/elastic#34]
The argument q= has no effect in the results. This is the result from querying 'JeSuisCharlie':

The results never match the query criteria. Check this out:

> Search(index="firehose", q="#JeSuisCharlie", size=2)$hits$hits -> test2; test2[[2]]$`_source`$text
[1] "RT @UnDislexico: —Tengo VIH y necesito confesarme.\n—Lo siento, no hay cura."

However, the JSON returned by the server (firehose/_search?q=JeSuisCharlie) works perfectly:

```
_index: "firehose",
_type: "status",
_id: "555434859586650113",
_score: 2.173656,
_source: {
text: "#IS: #JeSuisCharlie #AlQuaida: non! #JeSuisCharlie! #musilmans: nous sommes tous Charlie!",
created_at: "2015-01-14T18:42:44.000Z",
source: "<a href="http://twitter.com/#!/download/ipad" rel="nofollow">Twitter for iPad</a>",
```

Am I missing something or there's a problem with the function Search when parsing the argument "q"?

**Comment by sckott** [comment]
hi @herrcafe - thanks for your question. looking at it now

**Comment by sckott** [comment]
@herrcafe turns out I wasn't passing on the `q` parameter into the query sent to elasticsearch  - sorry about that. Try installing from Github again, and trying the query again. Let me know if it works...

**Comment by herrcafe** [comment]
Brill. Trying it right now. 

On a related note, have you considered implementing the scroll function to the Search function? Pagination (using size and from) is not ideal for large datasets.

**Comment by herrcafe** [comment]
Working fine now. Check it out:

> Search(index="firehose", q="#JeSuisCharlie", size=2)$hits$hits -> test2; test2[[2]]$`_source`$text
[1] "#IS: #JeSuisCharlie #AlQuaida: non! #JeSuisCharlie! #musilmans: nous sommes tous Charlie!"

**Comment by sckott** [comment]
great, good news :+1: 

looking at scrolling search now, in a new issue = #36

**Comment by sckott** [comment]
closing this - if there are further problems, we can reopen

**Comment by herrcafe** [comment]
Great work. Thanks!
