### ISSUE TITLE
docs_mget: Error in status_code(x) : object 'out' not found

### ISSUE THREAD

**Issue by arnauldvm** [ropensci/elastic#42]
Don't know how to debug this error returned by the elasticsearch library:

```R
> library('elastic')
> connect()
```
```text
uri:       http://127.0.0.1 
port:      9200 
username:  NULL 
password:  NULL 
api key:   NULL 
elasticsearch details:   
      status:                  200 
      name:                    Crimson Dynamo 
      Elasticsearch version:   1.2.1 
      ES version timestamp:    2014-06-03T15:02:52Z 
      lucene version:          4.8
```
```R
> index="logstash-XXXX-*"
> type="my_type"
> query="service:yyyy"
> count(index=index, type=type, q=query)
```
```text
[1] 510058
```
```R
> results = docs_mget(index=index, type=type, fields=c("timestamp", "duration_ms", "service"), q=query)
```
```text
Error in status_code(x) : object 'out' not found
```

* Windows 7 64b
* R engine 3.1.2, RStudio 0.98.1091, elastic library 0.3.0
* elasticsearch 1.2.2

**Comment by sckott** [comment]
@arnauldvm i changed `docs_mget()` to check the input parameters more thoroughly and throw errors when they aren't passed in correctly. 

As with `docs_get()` you need to pass in the `ids` parameter along with `index` and `type`. 

OR, you can pass in `index` and `type_id` params (for getting ids from different types within one index)
OR, pass in just `index_type_id` (for getting any number of ids across different indexes)

**Comment by arnauldvm** [comment]
I now get the following error:
```
Error: If type_id and index_type_id are NULL, you must pass in index, type, and ids
```

Fine for me.

**Comment by sckott** [comment]
great
