### ISSUE TITLE
docs_get: length(url) == 1 is not TRUE

### ISSUE THREAD

**Issue by arnauldvm** [ropensci/elastic#43]
Don't know how to debug this error returned by the elasticsearch library:

```R
> library('elastic')
> connect()
```
```text
uri:       http://127.0.0.1 
port:      9200 
username:  NULL 
password:  NULL 
api key:   NULL 
elasticsearch details:   
      status:                  200 
      name:                    Crimson Dynamo 
      Elasticsearch version:   1.2.1 
      ES version timestamp:    2014-06-03T15:02:52Z 
      lucene version:          4.8
```
```R
> index="logstash-XXXX-*"
> type="my_type"
> query="service:yyyy"
> count(index=index, type=type, q=query)
```
```text
[1] 510058
```
```R
> results = docs_get(index=index, type=type, fields=c("timestamp", "duration_ms", "service"), q=query, verbose=TRUE)
```
```text
Error: length(url) == 1 is not TRUE
```

* Windows 7 64b
* R engine 3.1.2, RStudio 0.98.1091, elastic library 0.3.0
* elasticsearch 1.2.2

**Comment by sckott** [comment]
@arnauldvm try it again after reinstalling, i just sent a commit https://github.com/ropensci/elastic/commit/6563274cbdb40adcabd8bf2cb48c2eedb723b10f

the `id` parameter is a required parameter for the get document API, so I changed it to be required. you should now get an error if you don't pass `id`

**Comment by arnauldvm** [comment]
I now get the error:
```
Error in sprintf("%s/%s/%s/%s", url, index, type, id) : 
  argument "id" is missing, with no default
```

How about the same kind of message as for docs_mget?

**Comment by sckott** [comment]
@arnauldvm hmm, i can't do that because `docs_mget()` has multiple options of data input in which you can (as explained in #42 )

* pass in only `ids`, and `index`, and `type`, OR
* pass in only `index` and `type_id` (for getting ids from different types within one index), OR
* pass in only `index_type_id` (for getting any number of ids across different indexes)

these are to support different use cases

**Comment by sckott** [comment]
closing, seems solved
