### ISSUE TITLE
scroll does not seem to handle long scroll_id properly

### ISSUE THREAD

**Issue by arnauldvm** [ropensci/elastic#44]
I have lots of shards, and that results in very long scroll_id's (e.g. 6961 characters long).
As per [the documentation of elasticsearch](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-scroll.html), these should be sent in the body of the request.

It works perfectly with curl, but not in R:
```R
> results = Search(index=index, type=type, q=query, fields=fields, scroll="1m", search_type = "scan")
> scroll_id = results$`_scroll_id`
> results = scroll(scroll_id=scroll_id, scroll="1m")
```
```text
Error in function (type, msg, asError = TRUE)  : Empty reply from server
```
Using the body also does not work:
```R
> results = scroll(body=list(scroll_id), scroll="1m")
```
```text
Error in search_POST(path = "_search/scroll", args = list(scroll = scroll,  : 
  formal argument "body" matched by multiple actual arguments
```

**Comment by arnauldvm** [comment]
Shouldn't the code
```R
search_POST(path = "_search/scroll", args=list(scroll=scroll, scroll_id=scroll_id), body=NULL, raw=raw, ...)
```
be replace by something like this:
```R
search_POST(path = "_search/scroll", args=list(scroll=scroll), body=scroll_id, raw=raw, ...)
```

**Comment by sckott** [comment]
thx for the report, i'll take a look

**Comment by sckott** [comment]
@arnauldvm okay, install again from github and try it - should work now. install instructions from github https://github.com/ropensci/elastic#install-elastic

**Comment by arnauldvm** [comment]
Thx, I'll try this...

**Comment by arnauldvm** [comment]
Tried today your latest version (installed directly from github), and it does the job.
Thanx very much!

**Comment by sckott** [comment]
great!
