### ISSUE TITLE
Unhandy termination when server failure response contains no error description

### ISSUE THREAD

**Issue by arnauldvm** [ropensci/elastic#45]
Cf `error_parser function` + `search_POST`/`scroll_POST` ...
In case of error retruned from the server (i.e. `tt$status_code > 202`), and in *specific* circumstances,
if might happen that `content(tt)` has no `$error member`.

Hence the first test in `error_parser` fails like this:
```
Error in if (grepl("SearchParseException", y)) { : 
  argument is of length zero
```

-> Would be nice to fail more gracefully.

It happened to me after retrieving 3M+ records from my ES server.
(A quite extreme condition I must admit, memory was almost full, might be the root cause of the problem)
(=> would be hard to reproduce, also.)

**Comment by sckott** [comment]
@arnauldvm thanks for the report.  I'm about to push a change that shouldn't cause that stop error in your case, but can you tell me what is returned in the body of that response that errored?  I assume it was just an empty body then?

**Comment by sckott** [comment]
@arnauldvm  you can reinstall and try again...

**Comment by sckott** [comment]
assume this is fixed due to inactivity
