### ISSUE TITLE
Search fails when using (big) numeric arguments

### ISSUE THREAD

**Issue by arnauldvm** [ropensci/elastic#46]
If the `from` argument is a numeric type and is very big (e.g. 100'000), the call to `Search` fails.

The reason is that the argument will be automatically converted to a string by `httr` (`build_url` function uses `paste0` which uses `as.character`).
But:
```R
> as.character(100000)
[1] "1e+05"
```
and ES does not expect this input.

My workaround is to use `from=sprintf("%d", current)` instead of `from=current`. (=> *not blocking*)
This is not expected because the documentation for `Search` describes implicitly `from` as a number.

(Note that my workaround does not work if `current` is already a string.)

I assume the same kind of issue could occur with `size`, though it's less likely to have big numbers for size.

**Comment by sckott** [comment]
k, will make a fix for this, you can always pass a number like `10000000L`, which won't get converted to sci. notation

**Comment by sckott** [comment]
i could adjust options like `options(scipen=999)` so that numbers passed in aren't converted to scientific notation, but that is considered bad practice as changing that option does it in the global namespace, will see how to do it just in the package namespace

**Comment by sckott** [comment]
@arnauldvm let me know if this works for you now, should be fixed.
