### ISSUE TITLE
Elasticsearch 1.2.1

### ISSUE THREAD

**Issue by tobiokanobi** [ropensci/elastic#47]
Dear Scott,

I have to access an elastic search 1.2.1 data base, but it seems like that it is not supported with elastic, isn't it? When I try to connect like

connect(es_base = "ubicity.ait.ac.at:8080/es/", es_user = NULL, es_pwd = NULL, es_key = NULL, force = FALSE)
(I tried it in several different versions)

I only get as return an empty error prompt
Error: (but no error message)

Is it because of ES 1.2.1 or because I screw it up?

Thx,

Tobias

**Comment by sckott** [comment]
hi @tobiokanobi - 

so `ubicity.ait.ac.at:8080/es/` + port `:9200` would lead to the elasticsearch DB? just making sure. that should work as the defaultl port if not specified is 9200

i'm looking into compabibility with other ES versions, more soon...

**Comment by tobiokanobi** [comment]
hi scott,

thanks for the fast reply! The port is 8080. As example, if I use rjson/jcurl and enter 

count <- fromJSON(getURL("http://ubicity.ait.ac.at:8080/es/twitter_all_geo/_count"))

I get the numbers of documents in "twitter_all_geo" as I expect it. Hence, I can access ES via URL.

**Comment by sckott** [comment]
ah, right, i haven't accounted for ES instances that don't require a port number. will push a change soon

**Comment by sckott** [comment]
okay @tobiokanobi can you try it again after reinstalling

```r
install.packages("devtools") # if you don't have devtools installed
devtools::install_github("ropensci/elastic")
```

the `connect()` function now doesn't set a port by default  - though since I do most of my dev on localhost:9200, i set `es_port = 9200` in my `.Rprofile` file, and this is read in. you can do the same for the base url via `es_base` if you want to set the default base url

**Comment by sckott** [comment]
now when you run `connect()` you should get 

```r
connect(es_base = "http://ubicity.ait.ac.at:8080/es")
```

```r
uri:       http://ubicity.ait.ac.at:8080/es 
port:       
username:  NULL 
password:  NULL 
api key:   NULL 
elasticsearch details:   
      status:                  200 
      name:                    NodeOne 
      Elasticsearch version:   1.2.1 
      ES version timestamp:    2014-06-03T15:02:52Z 
      lucene version:          4.8
```

**Comment by tobiokanobi** [comment]
Sckott,

**Comment by tobiokanobi** [comment]
Sckott, excellent! I'll try in an instance and thanks a lot for your support (you saved my thesis 😉)
-tobias

**Comment by tobiokanobi** [comment]
Tested and works fine Scott, thanks again for your help!

**Comment by sckott** [comment]
great
