### ISSUE TITLE
need support on geo filter

### ISSUE THREAD

**Issue by tobiokanobi** [ropensci/elastic#51]
Dear Scott,

I try hard to filter geo distance, and I tried to work it out according to your examples, but something goes wrong. Maybe you have an idea?

The error I get looks like that:

Error: SearchPhaseExecutionException[Failed to execute phase [query], all shards failed
1st shard:  [_PrRwo5wRTG9x0pPbGoPaQ][twitter_all_geo][1]: SearchParseException[[twitter_all_geo][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{  "query":{    "filtered":{      "filter":{        "geo_distance":"200km",        "ctweet.place.geo_point": {          "lon": 4,          "lat": 50        }      }    }  }}]]]; nested: QueryParsingException[[twitter_all_geo] [_na] filter malformed, no field after start_object];

The code I am using looks like this:

```r
body <- '{
  "query":{
    "filtered":{
      "filter":{
        "geo_distance":"200km",
        "place.geo_point": {
          "lon": 4,
          "lat": 50
        }
      }
    }
  }
}'
```

```r
connect(es_base = "http://ubicity.ait.ac.at:8080/es")
```

```r
out <- Search(index="twitter_all_geo",body=body)
out$hits$total
```

That's the mapping of the ES data base:

```r
mappings: {
ctweet: {
properties: {
msg: {
properties: {
text: {
type: string
}
lang: {
type: string
}
hash_tags: {
type: string
}
}
}
created_at: {
format: dateOptionalTime
type: date
}
id: {
type: string
}
place: {
properties: {
country: {
type: string
}
country_code: {
type: string
}
city: {
type: string
}
type: {
type: string
}
geo_point: {
type: geo_point
}
}
}
user: {
properties: {
name: {
type: string
}
}
}
}
}
``` 

Do you have an idea what goes wrong?

Thanks a lot!
-Tobias (and greetings from Austria)

**Comment by sckott** [comment]
@tobiokanobi thanks for the report. I put the code in code blocks, hope that's okay

**Comment by sckott** [comment]
Try the below, and tell me if it works. It just uses example data in the package

```r
library("elastic")

body <- '{
 "mappings": {
   "record": {
     "properties": {
         "location" : {"type" : "geo_point"}
      }
   }
 }
}'

index_create(index='gbifgeopoint', body=body)
path <- system.file("examples", "gbif_geopoint.json", package = "elastic")
docs_bulk(path)
```

Then query

```r
body <- '{
 "query":{
   "filtered":{
     "filter":{
        "geo_bounding_box" : {
          "location" : {
            "top_left" : {
              "lat" : 60,
              "lon" : 14
            },
            "bottom_right" : {
              "lat" : 40,
              "lon" : 1
            }
          }
       }
     }
   }
 }
}'
out <- Search('gbifgeopoint', body = body)
out$hits$total
do.call(rbind, lapply(out$hits$hits, function(x) x$`_source`$location))
```

If that works, then at least we have that in common.

**Comment by tobiokanobi** [comment]
@sckott absolutely (wow- thanks for the fast reply!)

I'll try it in a second!

**Comment by sckott** [comment]
your query may be malformed. I think following the docs here http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-filter.html you maybe want

```
body <- '{
  "query":{
    "filtered":{
      "filter":{
        "geo_distance": {
            "distance": "200km",
            "place.geo_point": {
                 "lon": 4,
                 "lat": 50
             }
         }
      }
    }
  }
}'
```

**Comment by tobiokanobi** [comment]
Scott, 

Thanks for your input! If I mark according the given example, it looks like that the query works, but...
```json
body <- '{
	"query" : {
  	  "filtered":{
		"query":{
			"match" : {"msg.lang":"de"}
		},
      	"filter":{
        	"geo_distance": {
			"distance" : "200km",
        		"ctweet.place.geo_point" : {
         		 	"lon": 50.4,
          			"lat": 30.6
					}
       			}
    			}
  		}
	}
}'
```
...but I get at the end this error when using the previously listed code :

**Error in y$error : Object of Type 'externalptr' is not subsetable**

Do you know why? I believe it has something to do with the used jsonlite package.

-Tobias

**Comment by sckott** [comment]
@tobiokanobi I don't think I have access to that server, it may be down right now. 

Anyway, does that query in your last comment work on the command line? In another context?  Just trying to make sure this is a problem in the elastic R package.

**Comment by sckott** [comment]
@tobiokanobi any feedback on this?

**Comment by tobiokanobi** [comment]
Still fighting...the es machine was down over the weekend. The query seems to fine now, but whatever I try, I get 0 results. I try now different type of queries, maybe I have a misunderstanding in between me ans ES queries...

**Comment by sckott** [comment]
Okay, well let me know what happens

**Comment by tobiokanobi** [comment]
Oh Scott...It works now. I found my i...mistake...it is case sensitive...so I simply put the language query in capital "DE", or "EN" and it works...

```R
library("RCurl")
library("elastic")


body <- '{
  "query":{
    "filtered":{
      "query":{
        "match" : {"msg.lang":"EN"}
      },
      "filter":{
       "geo_distance": {
        "distance":"100km",
        "place.geo_point": {
          "lon": 30.52193,
          "lat": 39.76548
         }
        }
      }
    }
  }
}'

connect(es_base = "http://ubicity.ait.ac.at:8080/es")
out <- Search(index="twitter_all_geo-2014-11-01",type="ctweet", body=body)
out$hits$total
```
My mistake is based on the fact, that if I query it with an simply URL, I can keep it lower case:
```R
url <- paste("http://ubicity.ait.ac.at:8080/es/twitter_all_geo/_search?fields=msg.text,created_at&q=msg.lang:de&size=", n, sep="")
json <- fromJSON(getURL(url), unexpected.escape = "keep")
tweets <- json$hits$hits
```

As a small remark: I tried different cmd and found that index_get can bring the following errors:
```R
index_get('twitter_all_geo-2014-11-01')
Error in content(z)$error : $ operator is invalid for atomic vectors
> index_get('twitter_all_geo-2014-11-01', features='mappings')
Error in content(z)$error : $ operator is invalid for atomic vectors
> index_get('twitter_all_geo-2014-11-01', features='state')
Error in content(z)$error : $ operator is invalid for atomic vectors
> index_get('twitter_all_geo-2014-11-01', features='ctweet')
Erro in content(z)$error : $ operator is invalid for atomic vectors
> 
```

But the following get_index seems to work (most likely because it has no entries):

```R
> index_get('twitter_all_geo-2014-11-01', features='aliases')
$`twitter_all_geo-2014-11-01`
$`twitter_all_geo-2014-11-01`$aliases
named list()
```

However...I am a big step further and pretty happy! Thanks for your package and your support!

-Tobias

**Comment by sckott** [comment]
Glad you got it working. 

What version of `elastic` are you using? and what version of `httr` do you have, you can just paste in output of `session_info()` or `sessionInfo()`

**Comment by tobiokanobi** [comment]
Okay..a little setback...if I run it against a much bigger database I still get the error:

'''R
> out <- Search(index="twitter_all_geo",type="ctweet", body=body)
Error in y$error : Objekt of Type 'externalptr' is not subsetable
'''
If I figure out on how to query just the index in steps, maybe something like from... to...

The output of sessionInfo
'''R
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] de_AT.UTF-8/de_AT.UTF-8/de_AT.UTF-8/C/de_AT.UTF-8/de_AT.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] elastic_0.3.1.999  rjson_0.2.15       ade4_1.6-2         SnowballC_0.5.1    wordcloud_2.5      RColorBrewer_1.1-2 tm_0.6            
 [8] NLP_0.1-5          RCurl_1.95-4.5     bitops_1.0-6       topicmodels_0.2-1 

loaded via a namespace (and not attached):
 [1] digest_0.6.8      httr_0.6.1        jsonlite_0.9.14   modeltools_0.2-21 parallel_3.1.2    Rcpp_0.11.3       ROAuth_0.9.5      slam_0.1-32      
 [9] stats4_3.1.2      stringr_0.6.2     tools_3.1.2       twitteR_1.1.7     XML_3.98-1.1    
'''

**Comment by sckott** [comment]
> If I figure out on how to query just the index in steps, maybe something like from... to...

See the parameters `from` and `size`

**Comment by sckott** [comment]
the error probably comes from here https://github.com/ropensci/elastic/blob/master/R/search.r#L82

I'm not sure why you're getting that though. That  line only triggers if you're HTTP status code indicates a problem happened with the Elasticsearch query.  So there is an error, but you are not getting that `error` element returned from the parsing of data that comes back from Elasticsearch

**Comment by sckott** [comment]
@tobiokanobi Okay, try reinstalling again from github `devtools::install_github("ropensci/elastic")` 

I changed the error parser a bit. I think it was failing on 504 errors, which is what I was getting, and I think you were getting, with your example code.  The 504 was returning a small html body that was failing to parse. Now `Search()` returns the 504 error correctly

**Comment by tobiokanobi** [comment]
@sckott 
Did and currently everything runs fine! Thanks - as I heard today, the server is a little bit on its limits and runs once in a while out of memory, causing the ES to fail.

Thanks...(but be sure that I have some more questions!)

-Tobias

**Comment by sckott** [comment]
great, glad to get more questions.
