### ISSUE TITLE
count: needs upper case in query term; search: needs lower case query term

### ISSUE THREAD

**Issue by tobiokanobi** [ropensci/elastic#56]
Dear Scott,

I found an interesting issue. If I run a  "search_type:count", the query needs in the term an upper case. But if I query "search" (with an aggregation), I need for the same query term an lower case. If I do it opposite I get zero return.

````R
#For whatever reason, the country code and language must be upper case in this query (UA, EN)
countUAlangEN <- '{
  "query": {
    "bool": {
      "must": [
         {"term": {"ctweet.place.country_code": "UA"}},
         {"term": {"ctweet.msg.lang":"EN"}}
      ],
      "must_not": [ ],
      "should": [ ]
    }
  },
  "sort": [ ],
  "facets": { }
}'
...
Search(index=nextElem(twitter.index), type="ctweet", search_type="count", body=countUAlangEN)$hits$total
 ````

But if I run this query,

````R

#For whatever reason, the country code and language must be lower case in this query (ua,en)
countUAlangEN <- '{
  "query": {
    "bool" : {
      "must" : [
        {"term": {"ctweet.place.country_code":"ua"}},
        {"term": {"ctweet.msg.lang":"en"}}
      ]
    }
  },
  "aggs": {
    "by_date": {
      "date_histogram": {
        "field": "created_at",
        "interval": "day",
        "format": "yyyy-MM-dd"
      }
    }
  }
}'
...
Search(index="twitter_all_geo", type="ctweet", body=countUAlangEN)
...
````
It took me some time to figure it out - not really a problem but a little bit annoying (late night, tired :-) )

Greetz,

Tobias

**Comment by sckott** [comment]
@tobiokanobi are you sure this difference in the two queries has to do with whether you use `search_type = count` or not?  What do these two queries do in a different client or on the command line?  Same result?  I'm trying here and not getting the same as you (but of course I don't have the same data)

**Comment by tobiokanobi** [comment]
That's very likely possible - it seems that at least one index has lower case entries, while most of them have upper case entries.

Sorry for bothering you with this matter!

-Tobias

**Comment by sckott** [comment]
@tobiokanobi do let me know if you get the same thing in another place, that is, not with this client, so that I know if I should change anything here
