### ISSUE TITLE
Bulk loading data from data frames

### ISSUE THREAD

**Issue by KrishnaPG** [ropensci/elastic#57]
With the `docs_bulk()` is it possible to load data that is already in memory (something like dataframe) ?

Looks like `docs_bulk` accepts only file as the argument - so wondering what is the right way to load data in bulk into ES from memory, such as data frames?

**Comment by sckott** [comment]
thanks for the question @KrishnaPG :0

I've actually just been thinking about this problem.  The elasticsearch bulk API only takes in a weird format http://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html  We can make this format easily of course, so its fine with small data.frames. But with very large data.frames, the time to create the file alone is quite a long time. I've been asking if the json client I use `jsonlite` can make this format for us (doesn't look promising though) jeroenooms/jsonlite#87

I will implement something soon, but it wont be great for large data.frames...

**Comment by sckott** [comment]
@KrishnaPG  what size data.frame's do you deal with?

**Comment by KrishnaPG** [comment]
Thanks @sckott The data frame sizes vary and could be quite large.

I agree with you about the time it takes to create the json (also the memory). 

However, I think its okay if it is documented that caller should take care of calling the `docs_bulk` only with batched rows (say 1000 at a time) and call it multiple times for large data frames in a loop (where they also get a chance to take care of the progress bar etc.) - so that `docs_bulk` itself need not to worry about the sizes of the frames (and caller will have to ensure to send dataframes in chunks to not stall the R).

Or, `docs_bulk` can accept a `batchSize` parameter along with complete dataframe and then process only `batchSize` no. of rows at a time, updating a progress bar before processing next batch in an internal loop. 

What do you think?

**Comment by sckott** [comment]
@KrishnaPG Okay, reinstall and try `docs_bulk()` with a data.frame. I don't have chunking yet, but think I should add it

**Comment by sckott** [comment]
@KrishnaPG okay, chunking added

**Comment by KrishnaPG** [comment]
@sckott  cool - worked right the first time - thanks much for the changes. Now we have a royal way to insert any data into ES :)

**Comment by sckott** [comment]
@KrishnaPG great, glad it works, no progress bar yet, might add that

**Comment by KrishnaPG** [comment]
BTW, been meaning to ask this for sometime, is there anyway these functions can be invoked through a namespace (something like `es::search` or `es.search` etc..). 

The reason is soon more will be adding their own packages (say for mongodb etc.) which may have their own connect, search etc. which will clutter the whole system. (I see already you had to make compromise with `Search`)

Besides, it sounds cool to type/read the code with `es.search(), es.connect(), es.ping(), es.docs_bulk()` so on, which makes the context pretty clear that we are dealing with `you know, for search` ;) 

Just a thought.

**Comment by sckott** [comment]
@KrishnaPG I have done that in other pkgs, though I kind of favor explicit namespacing e.g., `elastic::ping()` if there is a conflicting function name in another package, which you gave an example of above. Also, since this package is on CRAN i'd rather not break the package API

**Comment by KrishnaPG** [comment]
ok `elastic::` was what I was looking for (didn't know the namespace name). Will try it out  `elastic::search` etc. Thanks for the pointer.

**Comment by sckott** [comment]
progress bar added in 0e2bc6ce544bf537fbb0c9f19188845d504c223b @KrishnaPG
