### ISSUE TITLE
on windows system: cat_XXXX does not work while on OS X works

### ISSUE THREAD

**Issue by tobiokanobi** [ropensci/elastic#61]
Dear Scott,

My code works quite well on OS X, but today I tried to run the same on Windows, and I ran into the following issue:

all elastic cat_function() cause the following error :

````R
> cat_health
function (verbose = FALSE, index = NULL, fields = NULL, ...) 
cat_helper("health", v = verbose, i = index, f = fields, ...)
<environment: namespace:elastic>
> cat_health()
Error in as.character(function (description, open = "", blocking = TRUE,  : 
  cannot coerce type 'closure' to vector of type 'character'
> cat_health(verbose=FALSE)
Error in as.character(function (description, open = "", blocking = TRUE,  : 
  cannot coerce type 'closure' to vector of type 'character'
> cat_health(verbose=FALSE, index="twitter_all_geo")
Error in as.character(function (description, open = "", blocking = TRUE,  : 
  cannot coerce type 'closure' to vector of type 'character'
> library("httr")
> cat_health(verbose=FALSE)
Error in as.character(function (description, open = "", blocking = TRUE,  : 
  cannot coerce type 'closure' to vector of type 'character'
> cat_count(config=verbose(9))
Error in as.character(function (description, open = "", blocking = TRUE,  : 
  cannot coerce type 'closure' to vector of type 'character'
> cat_count(config=verbose())
Error in as.character(function (description, open = "", blocking = TRUE,  : 
  cannot coerce type 'closure' to vector of type 'character'
> cat_aliases()
Error in as.character(function (description, open = "", blocking = TRUE,  : 
  cannot coerce type 'closure' to vector of type 'character'
> cat_aliases(index='twitter_all_geo')
Error in as.character(function (description, open = "", blocking = TRUE,  : 
  cannot coerce type 'closure' to vector of type 'character'
> cat_aliases(index='twitter_all_geo')
Error in as.character(function (description, open = "", blocking = TRUE,  : 
  cannot coerce type 'closure' to vector of type 'character'
> cat_shards()
Error in as.character(function (description, open = "", blocking = TRUE,  : 
  cannot coerce type 'closure' to vector of type 'character'
> count(index='twitter_all_geo')
[1] 689437812
````
Same code - especially cat_indices, worked yesterday night fine on OS X.

I tried now to download and install the latest elastic package (using devtools), but now I have a hardtime to start a connection at all :-)

Greetz,

Tobias

P.S:
````R
> library(elastic)
> connect(es_base = "http://ubicity.ait.ac.at:8080/es")
Error:
````
And the loaded packages are: 
````R 
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=German_Austria.1252  LC_CTYPE=German_Austria.1252   
[3] LC_MONETARY=German_Austria.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Austria.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] elastic_0.3.4.99

loaded via a namespace (and not attached):
[1] bitops_1.0-6    httr_0.6.1      jsonlite_0.9.15 RCurl_1.95-4.5 
[5] stringr_0.6.2  
> 
````

**Comment by sckott** [comment]
hi - For the connection, I added `9200` back as the default port, so just set the port to NULL

`connect("http://ubicity.ait.ac.at:8080/es", NULL)`

Maybe there is a better way to do it, not sure. I imagine that it is common to have a port `9200` on elasticsearch instances for many people, but maybe not?

---------

For `cat_*()` functions: I'll look into that. I guess I hadn't really tested those functions on windows.

**Comment by sckott** [comment]
@tobiokanobi I'm trying this out on my windows virtual machine, and all the `cat_*()` functions work fine.  Do the cat_ functions work after you are connected correctly?

**Comment by tobiokanobi** [comment]
Scott,

the connection works with port=NULL again, and the cat*() commands as well.  Thanks - seems like that I updated the elastic package on my windows machine but not on my mac and this causes local confusion!

A small remark regarding ````R cat_indices() ````, the output is great, put if I try to assign it directly to a data frame, list or what so ever... with

````R
p <- cat_indices(verbose=TRUE)
````
p, the list, or the data.frame is always empty. It is necessary to capture the output

````R
indices.all <- as.list(capture.output(cat_indices(verbose=TRUE)))
````

Nice would be a format like 

http://ubicity.ait.ac.at:8080/es/_stats/indexes\?pretty=1

http://ubicity.ait.ac.at:8080/es/_stats/_aliases?pretty=1

Thanks Scott - I appreciate the time and effort you put into this project.

-Tobias

**Comment by sckott** [comment]
Hi @tobiokanobi the `cat`  APIs http://www.elastic.co/guide/en/elasticsearch/reference/current/cat.html work by printing text to the screen and are sort of meant for information purposes, and thus are not returned in json format, but in simple text format, e.g. see http://ubicity.ait.ac.at:8080/es/_cat/indices  

We could coerce the data from cat APIs into R structures, but at least that's not what they intended with those APIs.  Though I will see how easy it is across all cat APIs to optionally allow capturing data into a list or data.frame

To get stats on indices, see `index_stats()`, specifically `index_stats(metric = "indices")` in your case
