### ISSUE TITLE
Close text connections error

### ISSUE THREAD

**Issue by sckott** [ropensci/elastic#68]
With large data.frame's getting an error in `docs_bulk()` for text connections

```r
data(flights, package="nycflights13")
docs_bulk(flights, "flights")
  |============================                                                                                                            |  20%
 
 Error in textConnection(text, encoding = "UTF-8") : 
  all connections are in use 
```

**Comment by richfitz** [comment]
In `httr:::body_config` there is a non-closing file

```    if (inherits(body, "FileUploadInfo")) {
        con <- file(body$filename, "rb")
        mime_type <- body$contentType %||% mime::guess_type(body$filename, 
            empty = NULL)
        size <- file.info(body$filename)$size
        return(body_httr(post = TRUE, readfunction = function(nbytes, 
            ...) readBin(con, "raw", nbytes), postfieldsize = size, 
            type = mime_type))
    }
```

**Comment by sckott** [comment]
thanks!

well, it works (can load all of nycflghts, 370K rows in 1000 row chunks) if I close all connections at the end of each POST request, but i wonder if that's dangerous, e.g., https://github.com/ropensci/elastic/blob/conn/R/docs_bulk.r#L99

i played around with fiddling with `httr::body_config()`, but it's not exactly clear how to fix it, and anyway, would be hard to get a fix into httr i imagine

**Comment by richfitz** [comment]
I think a reasonable way of doing this would be to use the named temporary file approach (tempfile("elastic")) and then close all connections that we opened afterwards:

```r
closeAllConnections
tmpfile <- tempfile("elastic")
# approximately what's going on in body_config:
con <- file(tempfile)
open(con, "w")
# after POST:
cons <- showConnections()
ours <- as.integer(rownames(cons)[grepl("/elastic", cons[, "description"], fixed=TRUE)])
# this would show things are fine:
showConnections()
```

**Comment by richfitz** [comment]
Also: https://github.com/hadley/httr/pull/188

**Comment by sckott** [comment]
@richfitz right, named temp file it is. 

good find on that PR, been 3 months though :(
