### ISSUE TITLE
Connecting to 3rd Party Hosts Like Bonsai

### ISSUE THREAD

**Issue by abresler** [ropensci/elastic#69]
This probably should be in the service providers but does anyone know how to connect to outside clusters?  I have setup an account which provides you an amazon cluster URI but I am having trouble connecting anyone know what to do?

**Comment by sckott** [comment]
@abresler thx for the question. don't know. I'll look into this

**Comment by sckott** [comment]
signed up for an account - and seems to work fine, here's how it worked for me:

```r
connect("https://<bonsaiurl>", 
        es_port = NULL, 
        es_user = "<user name>", 
        es_pwd = "<password>")

# create from mtcars dataset
index_create("hello")
docs_bulk(mtcars, "hello", "world")
count("hello")

# from iris dataset
index_create("iris")
docs_bulk(iris, "iris", "flowers")
count("iris")
```

**Comment by sckott** [comment]
let me know if that worked @abresler @KrishnaPG

**Comment by abresler** [comment]
Will try again does it reference the amazon uri or the baseline bonsai one?

----------------------
Alex Bresler
abresler@asbcllc.com
​www.asbcllc.com​
917-455-0239​ (cell)​

**Comment by KrishnaPG** [comment]
Interesting. Was doing similar thing with `connect()` except I did not use the `es_port=NULL` parameter (thinking its optional and has default value).

Now, when I explicitly supply the `es_port=NULL` as one of the parameters - it started working fine. 

Cool. 

Thanks much @sckott Its very helpful.

**Comment by sckott** [comment]
@abresler its the bonsai url, e.g., `https://helloworld-1102077797.us-west-2.bonsai.io`

@KrishnaPG right, need port as `NULL`, since i mostly use it on my machine, i have a port 9200 as default - i can try and see if I can detect whether there is simply a port problem on connection, maybe even trying with 9200 and without automatically

**Comment by abresler** [comment]
That worked thanks guys!
