### ISSUE TITLE
how to work with SaaS / hosted ES servers? (https:// access trouble)

### ISSUE THREAD

**Issue by KrishnaPG** [ropensci/elastic#70]
To utilize hosted ES services (such as http://bonsai.io ), they provide `https://` access.

For example, one of our hosted ES clusters is: [https://4akklnpoaa:dt3rqjyspu@ghostlrn-3329452503.us-east-1.bonsai.io](https://4akklnpoaa:dt3rqjyspu@ghostlrn-3329452503.us-east-1.bonsai.io)

The above link works great if you put it directly into the browser. But, from this package, it is not clear how to make it work. For example, `connect("https://4akklnpoaa:dt3rqjyspu@ghostlrn-3329452503.us-east-1.bonsai.io")` did not work.

Tried `connect()` with just http:// and it seems connect fine, but has problems with docs_bulk. Below is the troubling code example:
````
connect("http://ghostlrn-3329452503.us-east-1.bonsai.io", es_user="4akklnpoaa", es_pwd="dt3rqjyspu")
shakespeare <- system.file("examples", "shakespeare_data.json", package = "elastic")
docs_bulk(shakespeare)
````
It gives, `Error in docs_bulk.character(shakespeare) : 
  Authorization is required to perform this request. Please provide credentials, or contact support@bonsai.io for assistance.` error.

**Comment by abresler** [comment]
Good timing on question same as mine!!

----------------------
Alex Bresler
abresler@asbcllc.com
​www.asbcllc.com​
917-455-0239​ (cell)​

**Comment by sckott** [comment]
see also #69

**Comment by KrishnaPG** [comment]
Sorry - I might have missed the earlier question #69 (searched for previous issues on `https://` and when found none raised the new issue). Some of our students at http://live.my-classes.com/ are using this package to load data into ES and was having issues with https:// - I was trying to find some quick solution / workaround to help them meet their weekly deadlines.

**Comment by sckott** [comment]
@KrishnaPG looking at it now

**Comment by KrishnaPG** [comment]
Thanks @sckott . By the way, if it helps, I found the below to be needed to make `https://` work without problem with RCurl

````
httpPUT("https://...", data, userpwd="secret:key", httpauth = 1L, ssl.verifypeer = FALSE)
````
The `httpauth` and `ssl.verifypeer` paramters were the key (to avoid certificate validation errors and auth mismatches). Just thought of sharing it here, in case it helps to implement similar thing inside the methods of this package.

**Comment by sckott** [comment]
@KrishnaPG Right, using `ssl.verifypeer` is not considered best practice though, and httr takes care of https well.  See #69 - i think you just need to set up connection correctly. let me know if that works.

**Comment by alaendle** [comment]
Just as a note for people that are running into a similar problem while trying to connect to a self-signed certificate. You could disable verification before calling connect.

library(httr)
set_config( config( ssl_verifypeer = 0L, ssl_verifyhost = 0L ) )
