### ISSUE TITLE
Error_'Calloc' could not allocate memory

### ISSUE THREAD

**Issue by zhengxiaochen** [ropensci/elastic#76]
Hello Sckott,
I met a memory problem when searching a large amount of data.
I was searching data hour by hour. It works fine at first, but after a few times, the error appears:
"Error in readBin(content, character()) : 
  'Calloc' could not allocate memory (47456329 of 1 bytes)"

I tried to restart the R session which didn't help. When I restart the computer, it came back to normal and appeared again after the same searching process.
When this problem happens, the Elasticsearch server was running well.

Here is the code I use to do the work:
     body <- list(query=list(range=list(peb_time=list(gte="20150620210000000", lte="20150620220000000"))))
    Search(index="pebble", type="mov", body=body, size=200000, sort="peb_time")

Do you have any idea why this happened? Did I do make some mistake? 

Thank you very much!
Zheng

**Comment by sckott** [comment]
hi @zhengxiaochen - Thanks for your report. 

I tried the same settings with some local data I have, but I can't replicate the problem. 

How much memory is on your machine?  When you have that problem, can you check to see if your computer's memory is low?  

One solution may be to simply split up the query into smaller chunks, e.g., 50,000 per query. 

Another option is using scrolling - see egs here https://github.com/ropensci/elastic/blob/master/man-roxygen/search_egs.r#L323-L358 Elasticsearch docs on scrolling https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html - It's intended for large data processing, so that may help you here.

**Comment by zhengxiaochen** [comment]
Hello @sckott  
Thank you very much for your reply.

The error happened again and I don't think it is because of the memory limitation of the machine. There is still enough free memory when it happened, as shown below:

             total       used       free     shared    buffers     cached
Mem:         12145       5521       6623         34        364       2017
-/+ buffers/cache:       3140       9005
Swap:         7627          0       7627

What I know is this error, "Error: cannot allocate vector of size xxx" is related to the R memory limits ( https://stat.ethz.ch/R-manual/R-devel/library/base/html/Memory-limits.html ). I searched for this topic and found many similar threads, but none of them, like gc() etc., solved my problem. 

Like you suggested, I was querying data by smaller chunks. The problem is that, the memory seems to be accumulating. It works well for the first few chunks, but after several times of querying, the error appeared. Then everything in R went wrong, even the libraries can not be loaded. Restarting the current R session didn't help, unless I restart the whole system. 

I am still trying to find the root cause now. This problem may be not related to the "elastic" package though.

It would be great if you could give some advice.

Thanks a lot.
Zheng

**Comment by sckott** [comment]
hi @zhengxiaochen - there is a new version of `httr` recently on CRAN, which is used inside `elastic`, that actually does that `readBin` call that you see the error for. 

Can you make sure you have the newest (`v1.0.0`), and try this again. If you get the same error, we can explore further from there.

**Comment by zhengxiaochen** [comment]
Hello @sckott ,
I checked the version of my httr package, it is the newest one (v1.0.0), as you can see here:

> packageDescription("httr") 
Package: httr
Version: 1.0.0
Title: Tools for Working with URLs and HTTP
Description: Useful tools for working with HTTP organised by HTTP verbs (GET(), POST(), etc). Configuration
            functions make it easy to control additional request components (authenticate(), add_headers()
            and so on).
Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre")), person("RStudio",
            role = "cph") )
Depends: R (>= 3.0.0)
Imports: digest, jsonlite, mime, curl (>= 0.6), R6, stringr (>= 0.6.1)
Suggests: base64enc, httpuv, jpeg, knitr, PKI (>= 0.1-2), png, testthat (>= 0.8.0), XML
VignetteBuilder: knitr
License: MIT + file LICENSE
URL: https://github.com/hadley/httr
NeedsCompilation: no
Packaged: 2015-06-24 20:35:50 UTC; hadley
Author: Hadley Wickham [aut, cre], RStudio [cph]
Maintainer: Hadley Wickham <hadley@rstudio.com>
Repository: CRAN
Date/Publication: 2015-06-25 12:14:59
Built: R 3.2.1; ; 2015-07-03 16:52:59 UTC; unix

The problem is still there. I couldn't solve it on my side.

Zheng

**Comment by sckott** [comment]
Sorry the problem persists. I have vacation now, but will try to figure this out when I get back

**Comment by sckott** [comment]
@zhengxiaochen does this problem persist?

**Comment by zhengxiaochen** [comment]
Hi @sckott , sorry for the delay. I just came back from holiday.
Actually the problem is still there. When the data set is large enough, the R session will crash and then everything goes wrong. 
This time when I was trying to replicate the error, the situation was even worse. It seems that the "devtools" package is damaged. The "elastic" package is not able to be installed due to the damage of "devtools". Then I tried to reinstall the "devtools" package and it failed too. I got the error:
```
    -------------------------------------------------------
    ERROR: configuration failed for package ‘xml2’
    * removing ‘/home/xiaochen/R/i686-pc-linux-gnu-library/3.2/xml2’
    Warning in install.packages :
      installation of package ‘xml2’ had non-zero exit status
    ERROR: dependency ‘xml2’ is not available for package ‘rversions’
    * removing ‘/home/xiaochen/R/i686-pc-linux-gnu-library/3.2/rversions’
    Warning in install.packages :
      installation of package ‘rversions’ had non-zero exit status
    ERROR: dependency ‘rversions’ is not available for package ‘devtools’
    * removing ‘/home/xiaochen/R/i686-pc-linux-gnu-library/3.2/devtools’
    Warning in install.packages :
      installation of package ‘devtools’ had non-zero exit status
    -----------------------------------------------------------
```
Now I am using the "RCurl" and "RJSONIO" packages to query from ES directly. I am still testing this method and it runs well till now.

Sorry I didn't find the root cause of this problem.
If you need more information from my side, please just let me know.

Zheng

**Comment by sckott** [comment]
Did you get devtools installed?  Looks like you needed to get `xml2` and `rversions` installed first.

**Comment by zhengxiaochen** [comment]
Hi @sckott, before I installed the "elastic" package, it is required to install "devtools" first. So I installed it successfully and the same to "elastic" package. It runs well for small size of data, but after several times of use, the above problem appeared. Then everything goes wrong. I can't load most of the packages including "elastic" "Rcurl" etc. and the "devtools" is also destroyed. Restarting the current R session doesn't help. After restarting the whole system, everything is normal again.
It seems that the use of buffer is accumulating every time the "Search" function is executed.
Currently I am using another method to do the same work so I don't have new information about this issue.

**Comment by sckott** [comment]
@zhengxiaochen thanks for the update - I'll try to get this sorted, still no solutions though

**Comment by zhengxiaochen** [comment]
@sckott Sorry I can't offer more information, as I am not so good at programming. Good Luck.

**Comment by sckott** [comment]
@zhengxiaochen have you updated to Elasticsearch v2 yet?  curious if that helps your problem at all, i imagine not, but worth a try
