### ISSUE TITLE
Error with count() with curl

### ISSUE THREAD

**Issue by damien-cremilleux** [ropensci/elastic#77]
Hello,

I am using elastic (v 0.4.0) to query elasticsearch (v 1.5.1).
When I try to count the number of documents for a given index (eg num <- elastic::count(index = "test")) I have the following error:
```
Error in curl::curl_escape(names(url$query)) : 
  `url` must be a character vector.
```
I can still search:
```
 s <- Search(index = "test")$hits
```
is correctly working.

Any idea on why this happens?

Thank you very much!
Damien

**Comment by sckott** [comment]
Sorry about that @damien-cremilleux - & thanks for the message. 

We use `httr` internally, which recently changed some of its internals, which creates that error. The dev version here in this repo has that fixed. 

Try installing like `devtools::install_github("ropensci/elastic")` and retry that. Let me know if it works

**Comment by damien-cremilleux** [comment]
Hello @sckott 

I just installed the dev version and it is now working.

Thanks a lot.
Damien

**Comment by sckott** [comment]
great, i'll get a new version to CRAN soon
