### ISSUE TITLE
[Question] how connection are closed?

### ISSUE THREAD

**Issue by happyshows** [ropensci/elastic#85]
Hi,

I'm new to elastic search, and I plan to use R shiny as the front end for queries.
Is there a proactive way to manage the connections? for example, call a disconnect() to close when R shiny session ends.

thanks.

**Comment by sckott** [comment]
@happyshows do you mean close the elasticsearch connection?  

If so, you can't do that from this R pkg. The R pkg doesn't start elaticsearch either. 

You have to start and stop elasticsearch on the command line. 

Once elasticsearch is running after you've started on the command line you run `connect()` (with any params) to set the connection. But there's no way to disconnect from within R. 

if the app will be on a server, you'll need access to the CLI

**Comment by happyshows** [comment]
it looks a bit weird to me (I use RDBMS in the past): to connect to ES I need to run connect() first, but when I'm done, I don't need to do anything? How the connection to ES is managed? Will this create numerous active connections after lots of web users used my R shiny application?

**Comment by sckott** [comment]
Right, I understand the difference here and with RDBMS's - we don't initialize a connection that can be closed as those do. 

`elastic` would create numerous connections.  Have you tested `elastic` with multiple clients in your Shiny app? I imagine it would be okay, but maybe not with a huge number of simultaneous users.  I'd be interested to see how it goes. 

If we really need ability to manage connections, we can explore adding that

**Comment by happyshows** [comment]
thanks, it will be a while before I can test that on shiny as I just started learning ES. I'll close this and reopen if necessary.

**Comment by sckott** [comment]
@happyshows okay, sounds good
