### ISSUE TITLE
[Question] how to bulk load docs with defined mapping?

### ISSUE THREAD

**Issue by happyshows** [ropensci/elastic#86]
Hi,

I'm not sure using 'mapping' is right term for ES. I'm experimenting to dump data frames to ES via this package.
For example, let's say I have a bunch of datasets (similar but with different version) and put them into /apple
dataset1:
appleID, attributes, Qty

dataset2 (data generated at a different time):
appleID, attributes, Qty

Is there a way to use docs_bulk to upload datasets to /apple/V1 ; /apple/V2 respectively? being able to 'map' it to a specific version will be more straight forward for end user.

Could you provide a minimal example, thanks...

**Comment by sckott** [comment]
yes, `docs_bulk()` has parameters `index` and `type` - types live within indices. So `apple` could be the index, and `V1`/`V2` the type's. 

Look at the docs for the bulk API if you haven't  yet https://www.elastic.co/guide/en/elasticsearch/guide/current/bulk.html

There are multiple operations you can do from that API, including index, create, update, and delete - If you pass in a file to `docs_bulk()` you can specify these different operations for each record. If you pass in a list or data.frame, there isn't currently a way to specify these different operations, we do the `index` operation for all records, which means 

> Create a new document or replace an existing document.

if you were updating a dataset, you could use the same index and type param inputs, then just update the records - would require passing in a vector of operation types, or maybe appending a column to a data.frame or a slot to a list with the desired operation

**Comment by happyshows** [comment]
Looks like index & type provides two layer hierarchy. What if I needed more than 2, say 4, 5?
for example, index = fruit, type = apple, 'sub_type'  = V1

all I can think of is to append a version column to apple, but I am not sure it is a good solution.

**Comment by sckott** [comment]
There are only indices and types within indices. That's all there is in terms of Elasticsearch structure. 

Documents in Elasticsearch have versions - see https://www.elastic.co/blog/versioning

So you could just update each document as it changes if you want - and you can go back to particular versions of a document if you wish

**Comment by happyshows** [comment]
looks like the intended use of versioning is for optimistic locking. In my case, I'll need to frequently query and compare different versions (and the version can't just be an incremental number, it has to be meaningfully assigned). for example
version: beginning of week, let's call it wk32
appleID, measure, Qty
fuji, inventory, 100
version: end of week, let's call it wk33
appleID, measure, Qty
fuji, inventory, 80

I need to upload both dataset to ES. while I need the capability to compare wk32 vs wk33.
should I create a 'version' column and fill in wk32 and wk33 respectively and then store as index=fruit, type = apple.

what I really want is to have wk(number) as the index, and then under it put /fruit/apple; /fruit/banana; etc. is this doable via ES? I want user to be able to access the data like below:
localhost:9200/wk32/fruit/apple
localhost:9200/wk32/fruit/banana

I know my question maybe more related to ES itself than your package, but thanks if you could point a direction for me to dig into :)

**Comment by sckott** [comment]
What you really want to do (e.g., `/wk32/fruit/apple`) isn't possible in elasticsearch - some discussion of basic concepts here https://www.elastic.co/guide/en/elasticsearch/reference/current/_basic_concepts.html which describes indices and types 

> while I need the capability to compare wk32 vs wk33.

what do  you mean? how will this comparison be done?

**Comment by sckott** [comment]
@happyshows what if you just concatenate two of the three things together e.g., 

`wk32fruit` as an index, then `apple` and `banana` as types within that index

then `wk33fruit`, `wk34fruit`, and so on

**Comment by happyshows** [comment]
yes this should work.

Can I do fuzzy search like index = 'wk32%' , type = 'apple', appleID = 'fuji' so that I can search fuji across different weeks?

Also, is there any downsides creating index based on concatenated names?

**Comment by sckott** [comment]
yeah, you can query against indices, searching against certain indices based on flexible terms - see https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html#multi-index

> Also, is there any downsides creating index based on concatenated names?

It would only be from your own user perspective. elasticsearch doesn't care what the index names are.  I guess you'll have more indices with this approach than if it was possible to do what you want to do, but again, not possible anyway.

**Comment by happyshows** [comment]
thanks a lot for the explanation :+1:

**Comment by sckott** [comment]
i guess I lied a little bit, elasticsearch does require that all index names are lowercase
