### ISSUE TITLE
Connection handling

### ISSUE THREAD

**Issue by sckott** [ropensci/elastic#87]
We may want to allow explicit handling of connections 

sparked from #85 

A related discussion in the python client repo elastic/elasticsearch-py#223

**Comment by sckott** [comment]
Since we're using the HTTP API, we can perhaps expose tools for users to deal with handles explicitly instead of just letting `httr` automagically deal with closing handles, etc. 

related hadley/httr#122

**Comment by sckott** [comment]
thinking of how to do this:

- use `R6` to create a connection object, this isn't like a DBI connection object to a C pointer, but rather a set of details for an ES instance (e.g., base url, port, basic auth user:pwd, etc.)
- should all methods live within the connection object, or pass the object into some methods, or something else?

How to transition from current setup

- is a package rename warranted giving how breaking the change is?
- could just do a big bump with the changes to e.g., `v0.9` to sorta indicate large changes, and in between use deprecation messages

**Comment by sckott** [comment]
It may make sense to roll out a new package timed with release of Elasticsearch v5 stable and that does explicit connection handling, cause both require lots of changes.

**Comment by sckott** [comment]
work on branch `r6-conn` https://github.com/ropensci/elastic/blob/r6-conn/R/Elasticsearch.R

**Comment by dpmccabe** [comment]
Could this include the ability to have connections to multiple servers? In other words, `connect` returns the connection details for one particular connection and functions like `docs_get` require this object as an argument. This would be similar to design patterns established in packages like DBI. As far as I can tell, there's no graceful way to query two ES instances in the same R script without constantly changing the global connection.

**Comment by sckott** [comment]
Yes, the new setup will allow multiple connections in the same R session. it will look something like (pseudocode)

```r
# the new connect() creates an R6 object
con1 <- connect(port = 9200)
con2 <- connect(port = 9300)
Search(con1, q = "foo")
Search(con2, q = "bar")
# with some methods on the R6 object itself
con1$ping()
```

**Comment by sckott** [comment]
@dpmccabe @happyshows @Jensxy @emillykkejensen @iainmwallace @kickbox 

Would love your feedback on a big change in the package. On branch [r6-conn](https://github.com/ropensci/elastic/tree/r6-conn) I've made it so that the `connect()` call creates an object that you need to pass to every function call. This makes it more explicit that you are interacting with a specific Elasticsearch instance, and you can manage any numbrer of different Elasticsearch instances within the same R session, whereas you could not before. 

here's a quick example:

```r
remotes::install_github("ropensci/elastic@r6-conn")
library(elastic)
x <- connect()
if (!index_exists(x, "shakespeare")) {
    shakespeare <- system.file("examples", "shakespeare_data.json", package = "elastic")
    invisible(docs_bulk(x, shakespeare))
}
Search(x, index="shakespeare", asdf=TRUE)
```

Would be curious to hear your experience with the new setup, and if there's anything we can do to make the transition easier. 

I'll probably bump a major version, to `v1.0`, since it's a big change. 

Another option was to put the functions as methods on the connection object, but there are so many functions that that would be cumbersome, so I opted to have the user pass the connection object to each function.

**Comment by happyshows** [comment]
I haven't run into a case where I need multiple connection in a session, but I think it would be helpful to have the new version look up a global default connection first (implicit connection) so that most of the code people have developed will be compatible with the latest version. (Maybe throw a warning to people to define connection explicitly in future?)

**Comment by sckott** [comment]
Thanks for your feedback @happyshows 

All new functions are like 

```r
foo <- function(conn, some_other_parameters) {
    is_conn(conn)
    # do some stuff
}
```

So the `conn` connection object is a required parmeter, and the `is_conn(conn)` line checks that the `conn` object is of the right type. 

We could set a default for `conn` like 

```r
foo <- function(conn = connect(), some_other_parameters) {
    is_conn(conn)
    # do some stuff
}
```

but the default is for localhost port 9200 , which I don't imagine is the default for most people? or is it?  but if we had a config file that connect pulls in I guess that would solve that, will think about that

----

The biggest issue in my mind going to this version from the previous one is that the first parameter of every function will have changed - but I don't see a way around that unless we put the connection parameter input as the last parameter, but that doesn't feel right. 

One option is putting all the functions as methods on the connection object, similar in feel to the python elasticsearch client, but using `x$method` instead of `x.method`. But I'd rather not do this as there's alot of code in this package, and it'd have to reorg a lot to make that happen.

**Comment by Jensxy** [comment]
I like the new feature to interact with a specific Elasticsearch instance. It is really useful if you have a development instance and a production instance. 

Good work!

**Comment by sckott** [comment]
all sorted now AFAICT ton the `r6-conn` branch. Closing this now. Will continue to add work on top of that branch until close to ready to release v1 to cran
