### ISSUE TITLE
Double quotes and backslashes are not escaped

### ISSUE THREAD

**Issue by Dmitrii-I** [ropensci/elastic#91]
When passing string `monitor 30"` to body of a query, it seems you are not escaping that double quote. You are actually expecting me to pass `monitor 30\"` it seems.

**Comment by sckott** [comment]
I'll have a look. You are using the `Search()` function? Passing to the `body`?

**Comment by Dmitrii-I** [comment]
Hi Scott,

Yes, using Search, passing to the body. I am going to debug couple hours
see if I can pinpoint it.

Cheers
Dmitrii

On Mon, Oct 19, 2015 at 5:30 PM, Scott Chamberlain <notifications@github.com

**Comment by Dmitrii-I** [comment]
All is fine with elastic actually. Its elastic search giving issues:

Browse[2]> content(tt)$error
[1] "SearchPhaseExecutionException[Failed to execute phase
[query_fetch], all shards failed; shardFailures
{[fjhbJVNnSiyYcT8eCv85GA][ads][0]: SearchParseException[[ads][0]:
from[-1],size[-1]: Parse Failure [Failed to parse source
[{\"query\":{\"bool\":{\"must\":[{\"query_string\":{\"default_field\":\"subject\",\"default_operator\":\"AND\",\"query\":\"macbook
13\\\"\",\"minimum_should_match\":\"75%\"}}]}}}]]]; nested:
QueryParsingException[[ads] Failed to parse query [macbook 13\"]];
nested: ParseException[Cannot parse 'macbook 13\"': Lexical error at
line 1, column 12.  Encountered: <EOF> after : \"\"]; nested:
TokenMgrError[Lexical error at line 1, column 12.  Encountered: <EOF>
after : \"\"]; }]"



The gihub issue can be closed.

Cheers
Dmitiri

On Mon, Oct 19, 2015 at 5:30 PM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
I was playing with this for a while. I __think__ it is an Elasticsearch issue, of properly escaping reserved characters - see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters for those

**Comment by Dmitrii-I** [comment]
Thats funny I am referencing exactly this page to build a function to
replace these characters in user input.

Thanks

On Mon, Oct 19, 2015 at 7:05 PM, Scott Chamberlain <notifications@github.com
